package com.bohai.dataCenter.persistence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;

import com.bohai.dataCenter.entity.CapitalStatement;

public interface CapitalStatementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int insert(CapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int insertSelective(CapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    CapitalStatement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int updateByPrimaryKeySelective(CapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int updateByPrimaryKey(CapitalStatement record);
    
    @Delete("delete from T_CAPITAL_STATEMENT")
    int deleteAll();
    
    /**
     * 根据交易日和投资者编号查询资金对账信息
     * @param tradeDate 交易日
     * @param investorNo 投资者编号
     * @return
     */
    CapitalStatement selectByTradeDateAndInvestorNo(String tradeDate, String investorNo);
    
    /**
     * 查询居间人名下所有客户的资金信息
     * @param mediatorNo
     * @return
     */
    List<CapitalStatement> selectByMediatorNo(String mediatorNo,String year,String month);
    
    /**
     * 查询客户资金信息
     * @param investorNo
     * @return
     */
    List<CapitalStatement> selectByInvestorNo(String investorNo,String year,String month);
    
    @Select("select t1.MARKETER_NO,t1.MARKETER_NAME,t1.DEP_NAME, t.* from T_CAPITAL_STATEMENT t ,T_MARKETER t1 "
            + "where F_GETMARKETERNO(t.INVESTOR_NO) is not null "
            + "and t1.MARKETER_NO = F_GETMARKETERNO(t.INVESTOR_NO)"
            + "and substr(t.TRADE_DATE_STR,0,6) = #{0} "
            + "and not EXISTS (select 1 "
            + "                from T_REPORT_REBATE t1 "
            + "               where t.INVESTOR_NO = t1.INVESTOR_NO)")
    
    List<Map<String,Object>> selectByExistsMarketer(String month);
    
    /**
     * 
     * 填充节假日资金调用存储过程
     * @param month
     */
    void callInterestReport(String month);
}