package com.bohai.dataCenter.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Delete;

import com.bohai.dataCenter.entity.CapitalStatement;

public interface CapitalStatementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int insert(CapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int insertSelective(CapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    CapitalStatement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int updateByPrimaryKeySelective(CapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_STATEMENT
     *
     * @mbggenerated Mon Apr 10 09:25:39 CST 2017
     */
    int updateByPrimaryKey(CapitalStatement record);
    
    @Delete("delete from T_CAPITAL_STATEMENT")
    int deleteAll();
    
    /**
     * 根据交易日和投资者编号查询资金对账信息
     * @param tradeDate 交易日
     * @param investorNo 投资者编号
     * @return
     */
    CapitalStatement selectByTradeDateAndInvestorNo(String tradeDate, String investorNo);
    
    /**
     * 查询居间人名下所有客户的资金信息
     * @param mediatorNo
     * @return
     */
    List<CapitalStatement> selectByMediatorNo(String mediatorNo,String year,String month);
    
    /**
     * 查询客户资金信息
     * @param investorNo
     * @return
     */
    List<CapitalStatement> selectByInvestorNo(String investorNo,String year,String month);
}