package com.bohai.dataCenter.persistence;

import java.util.Date;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;

import com.bohai.dataCenter.entity.CloseData;

public interface CloseDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DATA
     *
     * @mbggenerated Mon Apr 17 16:27:40 CST 2017
     */
    int insert(CloseData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DATA
     *
     * @mbggenerated Mon Apr 17 16:27:40 CST 2017
     */
    int insertSelective(CloseData record);
    
    @Select("select count(1) from t_close_data where DEAL_SERIAL = #{1} and INVESTOR_NO = #{0} and TRADE_DATE = #{2}")
    int countByInvestorNoAndSerial(String investor, String serial, String tradeDate);
    
    @Delete("delete from t_close_data where trade_Date = #{0}")
    int removeByDate(String date);
}