package com.bohai.dataCenter.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.bohai.dataCenter.entity.CrmCustomer;
import com.bohai.dataCenter.entity.CrmMarketer;
import com.bohai.dataCenter.entity.CrmMediator;
import com.bohai.dataCenter.vo.QueryCrmCustomerParamVO;

public interface CrmCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int deleteByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int insert(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int insertSelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    CrmCustomer selectByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int updateByPrimaryKeySelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int updateByPrimaryKey(CrmCustomer record);
    
    List<CrmCustomer> selectByCondition(QueryCrmCustomerParamVO paramVO);
    
    @Update("update T_CRM_CUSTOMER "
            + "set DEPT_CODE = #{depCode}"
            + "where BELONG_TYPE = '1'"
            + "and BELONG_TO = #{marketerNo}")
    int updateDepByMarketer(CrmMarketer marketer);
    
    @Update("update T_CRM_CUSTOMER "
            + "set DEPT_CODE = #{depCode} "
            + "where BELONG_TYPE = '2' "
            + "and BELONG_TO = #{mediatorNo}")
    int updateDepByMediator(CrmMediator mediator);
    
    @Update("update T_CRM_CUSTOMER "
            + "set BELONG_TYPE = #{belongType},"
            + "BELONG_TO = #{belongTo}"
            + "where BELONG_TYPE = '2' "
            + "and BELONG_TO = #{mediatorNo}")
    int updateBelongByMediator(CrmMediator mediator);
}