package com.bohai.dataCenter.persistence;

import java.util.List;

import com.bohai.dataCenter.entity.CrmCustomer;
import com.bohai.dataCenter.vo.QueryCrmCustomerParamVO;

public interface CrmCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int deleteByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int insert(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int insertSelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    CrmCustomer selectByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int updateByPrimaryKeySelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_CUSTOMER
     *
     * @mbggenerated Wed May 10 17:08:23 CST 2017
     */
    int updateByPrimaryKey(CrmCustomer record);
    
    List<CrmCustomer> selectByCondition(QueryCrmCustomerParamVO paramVO);
}