package com.bohai.dataCenter.persistence;

import com.bohai.dataCenter.entity.CrmMarketerHistory;

public interface CrmMarketerHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER_HISTORY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    int insert(CrmMarketerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER_HISTORY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    int insertSelective(CrmMarketerHistory record);
}