package com.bohai.dataCenter.persistence;

import java.util.List;

import com.bohai.dataCenter.entity.CrmMediatorHistory;
import com.bohai.dataCenter.vo.CrmMediatorAndCustomer;
import com.bohai.dataCenter.vo.QueryCrmMediatorParamVO;

public interface CrmMediatorHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR_HISTORY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    int insert(CrmMediatorHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR_HISTORY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    int insertSelective(CrmMediatorHistory record);
    
    
    List<CrmMediatorHistory> selectByCondition(QueryCrmMediatorParamVO paramVO);
    
    List<CrmMediatorAndCustomer> selectMediatorCustomerRelation(QueryCrmMediatorParamVO paramVO);
    
    
}