package com.bohai.dataCenter.persistence;

import java.util.List;

import com.bohai.dataCenter.entity.CrmMediator;
import com.bohai.dataCenter.vo.QueryCrmMediatorParamVO;

public interface CrmMediatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int deleteByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int insert(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int insertSelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    CrmMediator selectByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int updateByPrimaryKey(CrmMediator record);
    
    List<CrmMediator> selectByCondition(QueryCrmMediatorParamVO paramVO);
}