package com.bohai.dataCenter.persistence;

import java.util.List;

import com.bohai.dataCenter.entity.CrmMarketer;
import com.bohai.dataCenter.vo.QueryCrmMarketerParamVO;

public interface CrmMarketerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    int deleteByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    int insert(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    int insertSelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    CrmMarketer selectByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    int updateByPrimaryKey(CrmMarketer record);
    
    List<CrmMarketer> selectByCondition(QueryCrmMarketerParamVO paramVO);
}