package com.bohai.dataCenter.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.bohai.dataCenter.entity.CrmMarketer;
import com.bohai.dataCenter.entity.CrmMediator;
import com.bohai.dataCenter.vo.QueryCrmMediatorParamVO;

public interface CrmMediatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int deleteByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int insert(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int insertSelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    CrmMediator selectByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MEDIATOR
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    int updateByPrimaryKey(CrmMediator record);
    
    List<CrmMediator> selectByCondition(QueryCrmMediatorParamVO paramVO);
    
    @Update("update T_CRM_MEDIATOR "
            + "set DEP_CODE = #{depCode},"
            + "DEP_NAME = #{depName} "
            + "where BELONG_TYPE = '1' "
            + "and BELONG_TO = #{marketerNo}")
    int updateDepByMarketerNo(CrmMarketer marketer);
    
    List<CrmMediator> selectByMarketer(String marketerNo);
    
    @Select(" SELECT to_char(sysdate,'yymm')||'2'||lpad(SEQ_CRM_MEDIATORNO.nextval,5,'0') from dual")
    String getMediatorNo();
}