package com.bohai.dataCenter.persistence;

import java.util.List;

import com.bohai.dataCenter.entity.CrmMarketerHistory;
import com.bohai.dataCenter.vo.CrmMarketerAndCustomer;
import com.bohai.dataCenter.vo.CrmMarketerAndMediator;
import com.bohai.dataCenter.vo.QueryCrmMarketerParamVO;

public interface CrmMarketerHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER_HISTORY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    int insert(CrmMarketerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CRM_MARKETER_HISTORY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    int insertSelective(CrmMarketerHistory record);
    
    
    List<CrmMarketerHistory> selectByCondition(QueryCrmMarketerParamVO paramVO);
    
    
    List<CrmMarketerAndMediator> selectMaketerRelation(QueryCrmMarketerParamVO paramVO);
    
    List<CrmMarketerAndCustomer> selectMaketerCustomerRelation(QueryCrmMarketerParamVO paramVO);
    
}