package com.bohai.dataCenter.persistence;

import com.bohai.dataCenter.entity.CustTrade;

public interface CustTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUST_TRADE
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    int insert(CustTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUST_TRADE
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    int insertSelective(CustTrade record);
}