package com.bohai.dataCenter.persistence;

import com.bohai.dataCenter.entity.InstrumentAttribute;

public interface InstrumentAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INSTRUMENT_ATTRIBUTE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    int deleteByPrimaryKey(String instrument);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INSTRUMENT_ATTRIBUTE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    int insert(InstrumentAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INSTRUMENT_ATTRIBUTE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    int insertSelective(InstrumentAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INSTRUMENT_ATTRIBUTE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    InstrumentAttribute selectByPrimaryKey(String instrument);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INSTRUMENT_ATTRIBUTE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    int updateByPrimaryKeySelective(InstrumentAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INSTRUMENT_ATTRIBUTE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    int updateByPrimaryKey(InstrumentAttribute record);
}