package com.bohai.dataCenter.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Delete;

import com.bohai.dataCenter.entity.MarketerCust;

public interface MarketerCustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_CUST
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_CUST
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int insert(MarketerCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_CUST
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int insertSelective(MarketerCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_CUST
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    MarketerCust selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_CUST
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int updateByPrimaryKeySelective(MarketerCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_CUST
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int updateByPrimaryKey(MarketerCust record);
    
    int batchInsert(List<MarketerCust> records);
    
    @Delete("delete from T_MARKETER_CUST")
    int deleteAll();
}