package com.bohai.dataCenter.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Delete;

import com.bohai.dataCenter.entity.MarketerMediator;

public interface MarketerMediatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_MEDIATOR
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_MEDIATOR
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int insert(MarketerMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_MEDIATOR
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int insertSelective(MarketerMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_MEDIATOR
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    MarketerMediator selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_MEDIATOR
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int updateByPrimaryKeySelective(MarketerMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_MARKETER_MEDIATOR
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    int updateByPrimaryKey(MarketerMediator record);
    
    int batchInsert(List<MarketerMediator> records);
    
    @Delete("delete from T_MARKETER_MEDIATOR")
    int deleteAll();
}