package com.bohai.dataCenter.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Delete;

import com.bohai.dataCenter.entity.Mediator;

public interface MediatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEDIATOR
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEDIATOR
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    int insert(Mediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEDIATOR
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    int insertSelective(Mediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEDIATOR
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    Mediator selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEDIATOR
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    int updateByPrimaryKeySelective(Mediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEDIATOR
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    int updateByPrimaryKey(Mediator record);
    
    int batchInsert(List<Mediator> records);
    
    @Delete("delete from T_MEDIATOR")
    int deleteAll();
    
    Mediator selectByMediatorNo(String mediatorNo);
}