package com.bohai.dataCenter.persistence;

import org.apache.ibatis.annotations.Delete;

import com.bohai.dataCenter.entity.OpenRecord;

public interface OpenRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPEN_RECORD
     *
     * @mbggenerated Wed Apr 05 09:39:27 CST 2017
     */
    int insert(OpenRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OPEN_RECORD
     *
     * @mbggenerated Wed Apr 05 09:39:27 CST 2017
     */
    int insertSelective(OpenRecord record);
    
    @Delete("delete from t_open_record")
    int deleteAll();
}