package com.bohai.dataCenter.persistence;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;

import com.bohai.dataCenter.entity.ReporteInvestorRebate;

public interface ReporteInvestorRebateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORTE_INVESTOR_REBATE
     *
     * @mbggenerated Mon May 22 16:38:06 CST 2017
     */
    int insert(ReporteInvestorRebate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORTE_INVESTOR_REBATE
     *
     * @mbggenerated Mon May 22 16:38:06 CST 2017
     */
    int insertSelective(ReporteInvestorRebate record);
    
    @Select("select count(1) from T_REPORTE_INVESTOR_REBATE where INVESTOR_NO = #{0} and MONTH = {1}")
    int countByInvestorNoAndMonth(String investorNo, String month);
    
    int updateSelective(ReporteInvestorRebate record);
    
    /**
     * 根据月份和投资者编号查询手续费返还
     * @param month
     * @param investorNo
     * @return
     */
    ReporteInvestorRebate selectByMonthAndInvestorNo(String month , String investorNo);
    
    @Delete("delete from T_REPORTE_INVESTOR_REBATE where month = #{0}")
    int deleteByMonth(String month);
}