package com.bohai.dataCenter.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.bohai.dataCenter.entity.ReportExchangeRebate;
import com.bohai.dataCenter.vo.QueryExchangeRebateParamVO;

public interface ReportExchangeRebateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_EXCHANGE_REBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    int insert(ReportExchangeRebate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_EXCHANGE_REBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    int insertSelective(ReportExchangeRebate record);
    
    /**
     * 根据统计月份和机构更新
     * @param record
     * @return
     */
    int updateSelective(ReportExchangeRebate record);
    
    @Select("select count(1) from T_REPORT_EXCHANGE_REBATE where MONTH = #{0} and DEP_NAME = #{1}")
    int countByMonthAndDep(String month,String depName);
    
    ReportExchangeRebate selectByMonthAndDep(String month,String depName);
    
    List<ReportExchangeRebate> selectByCondition(QueryExchangeRebateParamVO paramVO);
}