package com.bohai.dataCenter.persistence;

import java.util.List;
import java.util.Map;

import com.bohai.dataCenter.entity.ReportSpecialReturn;
import com.bohai.dataCenter.vo.QuerySpecialReturnReportParamVO;

public interface ReportSpecialReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_SPECIAL_RETURN
     *
     * @mbggenerated Tue May 23 15:52:48 CST 2017
     */
    int deleteByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_SPECIAL_RETURN
     *
     * @mbggenerated Tue May 23 15:52:48 CST 2017
     */
    int insert(ReportSpecialReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_SPECIAL_RETURN
     *
     * @mbggenerated Tue May 23 15:52:48 CST 2017
     */
    int insertSelective(ReportSpecialReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_SPECIAL_RETURN
     *
     * @mbggenerated Tue May 23 15:52:48 CST 2017
     */
    ReportSpecialReturn selectByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_SPECIAL_RETURN
     *
     * @mbggenerated Tue May 23 15:52:48 CST 2017
     */
    int updateByPrimaryKeySelective(ReportSpecialReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_REPORT_SPECIAL_RETURN
     *
     * @mbggenerated Tue May 23 15:52:48 CST 2017
     */
    int updateByPrimaryKey(ReportSpecialReturn record);
    
    /**
     * 根据条件查询交易所返还特例
     * @param paramVO
     * @return
     */
    List<ReportSpecialReturn> selectByCondition(QuerySpecialReturnReportParamVO paramVO);
    
    /**
     * 查询营销人员交易所返还
     * @param month
     * @return
     */
    List<Map<String,Object>> selectMarketerReturn(String month);
}