package com.bohai.dataCenter.persistence;

import java.util.List;
import java.util.Map;

import com.bohai.dataCenter.entity.SysPermission;

public interface SysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    SysPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int updateByPrimaryKeySelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int updateByPrimaryKey(SysPermission record);
    
    /**
     * 查询用户顶级权限
     * @param userId
     * @return
     */
    List<SysPermission> queryPermissionsSelective(Map<String,Object> map);
    
    List<SysPermission> queryPermissionsLeftJoinUserName(Map<String,Object> map);
    
    
}