package com.bohai.dataCenter.persistence;

import java.util.List;
import java.util.Map;

import com.bohai.dataCenter.entity.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    int updateByPrimaryKey(SysUser record);
    
    /**
     * 根据用户名查询用户信息
     * @param username
     * @return
     */
    SysUser queryUserByUsername(String username);
    
    /**
     * 查询用户
     * @param map
     * @return
     */
    List<SysUser> queryUsers(Map<String, Object> map);

}