package com.bohai.dataCenter.persistence;

import java.util.ArrayList;

import com.bohai.dataCenter.entity.SysUsersPermissions;

public interface SysUsersPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERS_PERMISSIONS
     *
     * @mbggenerated Thu Jul 20 10:14:17 CST 2017
     */
    int insert(SysUsersPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERS_PERMISSIONS
     *
     * @mbggenerated Thu Jul 20 10:14:17 CST 2017
     */
    int insertSelective(SysUsersPermissions record);
    
    ArrayList<SysUsersPermissions> select(String userName);
}