package com.bohai.dataCenter.persistence;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.bohai.dataCenter.entity.TradingDate;

public interface TradingDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADING_DATE
     *
     * @mbggenerated Mon Apr 10 16:24:31 CST 2017
     */
    int deleteByPrimaryKey(Date tdate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADING_DATE
     *
     * @mbggenerated Mon Apr 10 16:24:31 CST 2017
     */
    int insert(TradingDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADING_DATE
     *
     * @mbggenerated Mon Apr 10 16:24:31 CST 2017
     */
    int insertSelective(TradingDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADING_DATE
     *
     * @mbggenerated Mon Apr 10 16:24:31 CST 2017
     */
    TradingDate selectByPrimaryKey(Date tdate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADING_DATE
     *
     * @mbggenerated Mon Apr 10 16:24:31 CST 2017
     */
    int updateByPrimaryKeySelective(TradingDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADING_DATE
     *
     * @mbggenerated Mon Apr 10 16:24:31 CST 2017
     */
    int updateByPrimaryKey(TradingDate record);
    
    List<TradingDate> selectHolidaysByYearAndMonth(String year, String month);
    
    /**
     * 查询指定日期的前一交易日期
     * @param date
     * @return
     */
    @Select("select max(t.tdate) from T_TRADING_DATE t where t.tdate < #{0} and t.type = '1'")
    Date selectPreTraDateByDate(Date date);
}