package com.bohai.dataCenter.persistence;

import org.apache.ibatis.annotations.Select;

import com.bohai.dataCenter.entity.TradeData;

public interface TradeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_DATA
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    int insert(TradeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_DATA
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    int insertSelective(TradeData record);
    
    @Select("select count(1) from t_trade_data where SERIAL_NO = #{1} and INVESTOR_NO = #{0} and TRADE_DATE = #{2}")
    int countByInvestorNoAndSerial(String investor, String serial, String tradeDate);
}