package com.bohai.dataCenter.entity;

import java.util.Date;

public class CrmCustomerHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.INVESTOR_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.INVESTOR_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.FULL_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.STATUS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.DEPT_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.OPEN_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.CANCEL_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String cancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.OPEN_OPERATOR
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String openOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.CANCEL_OPERATOR
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String cancelOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.CERT_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.CERT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.POSTCODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.MOBILE_PHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.EMAIL
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.CONTRACT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.CUST_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.EFFECT_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String effectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.EXPIRE_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.BELONG_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String belongType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.BELONG_TO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String belongTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.INVESTOR_NO
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.INVESTOR_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.INVESTOR_NO
     *
     * @param investorNo the value for T_CRM_CUSTOMER_HISTORY.INVESTOR_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.INVESTOR_NAME
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.INVESTOR_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.INVESTOR_NAME
     *
     * @param investorName the value for T_CRM_CUSTOMER_HISTORY.INVESTOR_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName == null ? null : investorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.FULL_NAME
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.FULL_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.FULL_NAME
     *
     * @param fullName the value for T_CRM_CUSTOMER_HISTORY.FULL_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.STATUS
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.STATUS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.STATUS
     *
     * @param status the value for T_CRM_CUSTOMER_HISTORY.STATUS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.DEPT_CODE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.DEPT_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.DEPT_CODE
     *
     * @param deptCode the value for T_CRM_CUSTOMER_HISTORY.DEPT_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.OPEN_DATE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.OPEN_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.OPEN_DATE
     *
     * @param openDate the value for T_CRM_CUSTOMER_HISTORY.OPEN_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate == null ? null : openDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.CANCEL_DATE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.CANCEL_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.CANCEL_DATE
     *
     * @param cancelDate the value for T_CRM_CUSTOMER_HISTORY.CANCEL_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCancelDate(String cancelDate) {
        this.cancelDate = cancelDate == null ? null : cancelDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.OPEN_OPERATOR
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.OPEN_OPERATOR
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getOpenOperator() {
        return openOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.OPEN_OPERATOR
     *
     * @param openOperator the value for T_CRM_CUSTOMER_HISTORY.OPEN_OPERATOR
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setOpenOperator(String openOperator) {
        this.openOperator = openOperator == null ? null : openOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.CANCEL_OPERATOR
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.CANCEL_OPERATOR
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCancelOperator() {
        return cancelOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.CANCEL_OPERATOR
     *
     * @param cancelOperator the value for T_CRM_CUSTOMER_HISTORY.CANCEL_OPERATOR
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCancelOperator(String cancelOperator) {
        this.cancelOperator = cancelOperator == null ? null : cancelOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.CERT_TYPE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.CERT_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.CERT_TYPE
     *
     * @param certType the value for T_CRM_CUSTOMER_HISTORY.CERT_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.CERT_NO
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.CERT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.CERT_NO
     *
     * @param certNo the value for T_CRM_CUSTOMER_HISTORY.CERT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.POSTCODE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.POSTCODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.POSTCODE
     *
     * @param postcode the value for T_CRM_CUSTOMER_HISTORY.POSTCODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.ADDRESS
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.ADDRESS
     *
     * @param address the value for T_CRM_CUSTOMER_HISTORY.ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.TELEPHONE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.TELEPHONE
     *
     * @param telephone the value for T_CRM_CUSTOMER_HISTORY.TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.MOBILE_PHONE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.MOBILE_PHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.MOBILE_PHONE
     *
     * @param mobilePhone the value for T_CRM_CUSTOMER_HISTORY.MOBILE_PHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.EMAIL
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.EMAIL
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.EMAIL
     *
     * @param email the value for T_CRM_CUSTOMER_HISTORY.EMAIL
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.CONTRACT_NO
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.CONTRACT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.CONTRACT_NO
     *
     * @param contractNo the value for T_CRM_CUSTOMER_HISTORY.CONTRACT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.CUST_TYPE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.CUST_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.CUST_TYPE
     *
     * @param custType the value for T_CRM_CUSTOMER_HISTORY.CUST_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.REMARK
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.REMARK
     *
     * @param remark the value for T_CRM_CUSTOMER_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.EFFECT_DATE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.EFFECT_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getEffectDate() {
        return effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.EFFECT_DATE
     *
     * @param effectDate the value for T_CRM_CUSTOMER_HISTORY.EFFECT_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setEffectDate(String effectDate) {
        this.effectDate = effectDate == null ? null : effectDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.EXPIRE_DATE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.EXPIRE_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.EXPIRE_DATE
     *
     * @param expireDate the value for T_CRM_CUSTOMER_HISTORY.EXPIRE_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate == null ? null : expireDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.CREATE_TIME
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.CREATE_TIME
     *
     * @param createTime the value for T_CRM_CUSTOMER_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.UPDATE_TIME
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.UPDATE_TIME
     *
     * @param updateTime the value for T_CRM_CUSTOMER_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.BELONG_TYPE
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.BELONG_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getBelongType() {
        return belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.BELONG_TYPE
     *
     * @param belongType the value for T_CRM_CUSTOMER_HISTORY.BELONG_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setBelongType(String belongType) {
        this.belongType = belongType == null ? null : belongType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.BELONG_TO
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.BELONG_TO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getBelongTo() {
        return belongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.BELONG_TO
     *
     * @param belongTo the value for T_CRM_CUSTOMER_HISTORY.BELONG_TO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo == null ? null : belongTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER_HISTORY.DELETE_FLAG
     *
     * @return the value of T_CRM_CUSTOMER_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER_HISTORY.DELETE_FLAG
     *
     * @param deleteFlag the value for T_CRM_CUSTOMER_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}