package com.bohai.dataCenter.entity;

import java.util.Date;

public class CrmDeptHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.DEPT_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.DEPT_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.DEPT_TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deptTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.DEPT_ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deptAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.DEPT_HEAD
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deptHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.ESTABLISH_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private Date establishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.CREATE_BY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.UPDATE_BY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_DEPT_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.DEPT_CODE
     *
     * @return the value of T_CRM_DEPT_HISTORY.DEPT_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.DEPT_CODE
     *
     * @param deptCode the value for T_CRM_DEPT_HISTORY.DEPT_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.DEPT_NAME
     *
     * @return the value of T_CRM_DEPT_HISTORY.DEPT_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.DEPT_NAME
     *
     * @param deptName the value for T_CRM_DEPT_HISTORY.DEPT_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.DEPT_TELEPHONE
     *
     * @return the value of T_CRM_DEPT_HISTORY.DEPT_TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeptTelephone() {
        return deptTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.DEPT_TELEPHONE
     *
     * @param deptTelephone the value for T_CRM_DEPT_HISTORY.DEPT_TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeptTelephone(String deptTelephone) {
        this.deptTelephone = deptTelephone == null ? null : deptTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.DEPT_ADDRESS
     *
     * @return the value of T_CRM_DEPT_HISTORY.DEPT_ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeptAddress() {
        return deptAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.DEPT_ADDRESS
     *
     * @param deptAddress the value for T_CRM_DEPT_HISTORY.DEPT_ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeptAddress(String deptAddress) {
        this.deptAddress = deptAddress == null ? null : deptAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.DEPT_HEAD
     *
     * @return the value of T_CRM_DEPT_HISTORY.DEPT_HEAD
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeptHead() {
        return deptHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.DEPT_HEAD
     *
     * @param deptHead the value for T_CRM_DEPT_HISTORY.DEPT_HEAD
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeptHead(String deptHead) {
        this.deptHead = deptHead == null ? null : deptHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.ESTABLISH_DATE
     *
     * @return the value of T_CRM_DEPT_HISTORY.ESTABLISH_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public Date getEstablishDate() {
        return establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.ESTABLISH_DATE
     *
     * @param establishDate the value for T_CRM_DEPT_HISTORY.ESTABLISH_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setEstablishDate(Date establishDate) {
        this.establishDate = establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.CREATE_TIME
     *
     * @return the value of T_CRM_DEPT_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.CREATE_TIME
     *
     * @param createTime the value for T_CRM_DEPT_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.CREATE_BY
     *
     * @return the value of T_CRM_DEPT_HISTORY.CREATE_BY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.CREATE_BY
     *
     * @param createBy the value for T_CRM_DEPT_HISTORY.CREATE_BY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.UPDATE_TIME
     *
     * @return the value of T_CRM_DEPT_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.UPDATE_TIME
     *
     * @param updateTime the value for T_CRM_DEPT_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.UPDATE_BY
     *
     * @return the value of T_CRM_DEPT_HISTORY.UPDATE_BY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.UPDATE_BY
     *
     * @param updateBy the value for T_CRM_DEPT_HISTORY.UPDATE_BY
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.REMARK
     *
     * @return the value of T_CRM_DEPT_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.REMARK
     *
     * @param remark the value for T_CRM_DEPT_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_DEPT_HISTORY.DELETE_FLAG
     *
     * @return the value of T_CRM_DEPT_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_DEPT_HISTORY.DELETE_FLAG
     *
     * @param deleteFlag the value for T_CRM_DEPT_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}