package com.bohai.dataCenter.entity;

import java.util.Date;

public class CrmMediatorHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String mediatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String mediatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_SHORT_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String mediatorShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.STATUS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.DEP_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.DEP_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.ALLOCATION_PROPORTION
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String allocationProportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.PAY_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.FAX
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.EMAIL
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.CERT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.EFFECT_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String effectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.EXPIRE_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.CERT_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.BELONG_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String belongType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.BELONG_TO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String belongTo;
    
    private String belongToName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR_HISTORY.IS_IB
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    private String isIb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_NO
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.MEDIATOR_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getMediatorNo() {
        return mediatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_NO
     *
     * @param mediatorNo the value for T_CRM_MEDIATOR_HISTORY.MEDIATOR_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setMediatorNo(String mediatorNo) {
        this.mediatorNo = mediatorNo == null ? null : mediatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_NAME
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.MEDIATOR_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getMediatorName() {
        return mediatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_NAME
     *
     * @param mediatorName the value for T_CRM_MEDIATOR_HISTORY.MEDIATOR_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setMediatorName(String mediatorName) {
        this.mediatorName = mediatorName == null ? null : mediatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_SHORT_NAME
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.MEDIATOR_SHORT_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getMediatorShortName() {
        return mediatorShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.MEDIATOR_SHORT_NAME
     *
     * @param mediatorShortName the value for T_CRM_MEDIATOR_HISTORY.MEDIATOR_SHORT_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setMediatorShortName(String mediatorShortName) {
        this.mediatorShortName = mediatorShortName == null ? null : mediatorShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.STATUS
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.STATUS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.STATUS
     *
     * @param status the value for T_CRM_MEDIATOR_HISTORY.STATUS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.DEP_CODE
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.DEP_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.DEP_CODE
     *
     * @param depCode the value for T_CRM_MEDIATOR_HISTORY.DEP_CODE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.DEP_NAME
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.DEP_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.DEP_NAME
     *
     * @param depName the value for T_CRM_MEDIATOR_HISTORY.DEP_NAME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.ALLOCATION_PROPORTION
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.ALLOCATION_PROPORTION
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getAllocationProportion() {
        return allocationProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.ALLOCATION_PROPORTION
     *
     * @param allocationProportion the value for T_CRM_MEDIATOR_HISTORY.ALLOCATION_PROPORTION
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setAllocationProportion(String allocationProportion) {
        this.allocationProportion = allocationProportion == null ? null : allocationProportion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.PAY_TYPE
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.PAY_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.PAY_TYPE
     *
     * @param payType the value for T_CRM_MEDIATOR_HISTORY.PAY_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.TELEPHONE
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.TELEPHONE
     *
     * @param telephone the value for T_CRM_MEDIATOR_HISTORY.TELEPHONE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.FAX
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.FAX
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.FAX
     *
     * @param fax the value for T_CRM_MEDIATOR_HISTORY.FAX
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.ADDRESS
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.ADDRESS
     *
     * @param address the value for T_CRM_MEDIATOR_HISTORY.ADDRESS
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.EMAIL
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.EMAIL
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.EMAIL
     *
     * @param email the value for T_CRM_MEDIATOR_HISTORY.EMAIL
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.CERT_NO
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.CERT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.CERT_NO
     *
     * @param certNo the value for T_CRM_MEDIATOR_HISTORY.CERT_NO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.REMARK
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.REMARK
     *
     * @param remark the value for T_CRM_MEDIATOR_HISTORY.REMARK
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.CREATE_TIME
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.CREATE_TIME
     *
     * @param createTime the value for T_CRM_MEDIATOR_HISTORY.CREATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.UPDATE_TIME
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.UPDATE_TIME
     *
     * @param updateTime the value for T_CRM_MEDIATOR_HISTORY.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.EFFECT_DATE
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.EFFECT_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getEffectDate() {
        return effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.EFFECT_DATE
     *
     * @param effectDate the value for T_CRM_MEDIATOR_HISTORY.EFFECT_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setEffectDate(String effectDate) {
        this.effectDate = effectDate == null ? null : effectDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.EXPIRE_DATE
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.EXPIRE_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.EXPIRE_DATE
     *
     * @param expireDate the value for T_CRM_MEDIATOR_HISTORY.EXPIRE_DATE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate == null ? null : expireDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.CERT_TYPE
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.CERT_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.CERT_TYPE
     *
     * @param certType the value for T_CRM_MEDIATOR_HISTORY.CERT_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.BELONG_TYPE
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.BELONG_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getBelongType() {
        return belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.BELONG_TYPE
     *
     * @param belongType the value for T_CRM_MEDIATOR_HISTORY.BELONG_TYPE
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setBelongType(String belongType) {
        this.belongType = belongType == null ? null : belongType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.BELONG_TO
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.BELONG_TO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getBelongTo() {
        return belongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.BELONG_TO
     *
     * @param belongTo the value for T_CRM_MEDIATOR_HISTORY.BELONG_TO
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo == null ? null : belongTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.DELETE_FLAG
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.DELETE_FLAG
     *
     * @param deleteFlag the value for T_CRM_MEDIATOR_HISTORY.DELETE_FLAG
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR_HISTORY.IS_IB
     *
     * @return the value of T_CRM_MEDIATOR_HISTORY.IS_IB
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public String getIsIb() {
        return isIb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR_HISTORY.IS_IB
     *
     * @param isIb the value for T_CRM_MEDIATOR_HISTORY.IS_IB
     *
     * @mbggenerated Mon Jul 10 16:18:59 CST 2017
     */
    public void setIsIb(String isIb) {
        this.isIb = isIb == null ? null : isIb.trim();
    }

    public String getBelongToName() {
        return belongToName;
    }

    public void setBelongToName(String belongToName) {
        this.belongToName = belongToName;
    }
    
    
}