package com.bohai.dataCenter.entity;

import java.util.Date;

public class CrmMediator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String mediatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.MEDIATOR_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String mediatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.MEDIATOR_SHORT_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String mediatorShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.STATUS
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.DEP_CODE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.DEP_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.ALLOCATION_PROPORTION
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String allocationProportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.PAY_TYPE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.TELEPHONE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.FAX
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.ADDRESS
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.EMAIL
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.CERT_NO
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.REMARK
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.CREATE_TIME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.UPDATE_TIME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.EFFECT_DATE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String effectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.EXPIRE_DATE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.CERT_TYPE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    private String certType;
    
    private String belongType;
    
    private String belongTo;

    
    public String getBelongType() {
        return belongType;
    }

    public void setBelongType(String belongType) {
        this.belongType = belongType;
    }

    public String getBelongTo() {
        return belongTo;
    }

    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.MEDIATOR_NO
     *
     * @return the value of T_CRM_MEDIATOR.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getMediatorNo() {
        return mediatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.MEDIATOR_NO
     *
     * @param mediatorNo the value for T_CRM_MEDIATOR.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setMediatorNo(String mediatorNo) {
        this.mediatorNo = mediatorNo == null ? null : mediatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.MEDIATOR_NAME
     *
     * @return the value of T_CRM_MEDIATOR.MEDIATOR_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getMediatorName() {
        return mediatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.MEDIATOR_NAME
     *
     * @param mediatorName the value for T_CRM_MEDIATOR.MEDIATOR_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setMediatorName(String mediatorName) {
        this.mediatorName = mediatorName == null ? null : mediatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.MEDIATOR_SHORT_NAME
     *
     * @return the value of T_CRM_MEDIATOR.MEDIATOR_SHORT_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getMediatorShortName() {
        return mediatorShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.MEDIATOR_SHORT_NAME
     *
     * @param mediatorShortName the value for T_CRM_MEDIATOR.MEDIATOR_SHORT_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setMediatorShortName(String mediatorShortName) {
        this.mediatorShortName = mediatorShortName == null ? null : mediatorShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.STATUS
     *
     * @return the value of T_CRM_MEDIATOR.STATUS
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.STATUS
     *
     * @param status the value for T_CRM_MEDIATOR.STATUS
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.DEP_CODE
     *
     * @return the value of T_CRM_MEDIATOR.DEP_CODE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.DEP_CODE
     *
     * @param depCode the value for T_CRM_MEDIATOR.DEP_CODE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.DEP_NAME
     *
     * @return the value of T_CRM_MEDIATOR.DEP_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.DEP_NAME
     *
     * @param depName the value for T_CRM_MEDIATOR.DEP_NAME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.ALLOCATION_PROPORTION
     *
     * @return the value of T_CRM_MEDIATOR.ALLOCATION_PROPORTION
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getAllocationProportion() {
        return allocationProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.ALLOCATION_PROPORTION
     *
     * @param allocationProportion the value for T_CRM_MEDIATOR.ALLOCATION_PROPORTION
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setAllocationProportion(String allocationProportion) {
        this.allocationProportion = allocationProportion == null ? null : allocationProportion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.PAY_TYPE
     *
     * @return the value of T_CRM_MEDIATOR.PAY_TYPE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.PAY_TYPE
     *
     * @param payType the value for T_CRM_MEDIATOR.PAY_TYPE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.TELEPHONE
     *
     * @return the value of T_CRM_MEDIATOR.TELEPHONE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.TELEPHONE
     *
     * @param telephone the value for T_CRM_MEDIATOR.TELEPHONE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.FAX
     *
     * @return the value of T_CRM_MEDIATOR.FAX
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.FAX
     *
     * @param fax the value for T_CRM_MEDIATOR.FAX
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.ADDRESS
     *
     * @return the value of T_CRM_MEDIATOR.ADDRESS
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.ADDRESS
     *
     * @param address the value for T_CRM_MEDIATOR.ADDRESS
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.EMAIL
     *
     * @return the value of T_CRM_MEDIATOR.EMAIL
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.EMAIL
     *
     * @param email the value for T_CRM_MEDIATOR.EMAIL
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.CERT_NO
     *
     * @return the value of T_CRM_MEDIATOR.CERT_NO
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.CERT_NO
     *
     * @param certNo the value for T_CRM_MEDIATOR.CERT_NO
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.REMARK
     *
     * @return the value of T_CRM_MEDIATOR.REMARK
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.REMARK
     *
     * @param remark the value for T_CRM_MEDIATOR.REMARK
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.CREATE_TIME
     *
     * @return the value of T_CRM_MEDIATOR.CREATE_TIME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.CREATE_TIME
     *
     * @param createTime the value for T_CRM_MEDIATOR.CREATE_TIME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.UPDATE_TIME
     *
     * @return the value of T_CRM_MEDIATOR.UPDATE_TIME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.UPDATE_TIME
     *
     * @param updateTime the value for T_CRM_MEDIATOR.UPDATE_TIME
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.EFFECT_DATE
     *
     * @return the value of T_CRM_MEDIATOR.EFFECT_DATE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getEffectDate() {
        return effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.EFFECT_DATE
     *
     * @param effectDate the value for T_CRM_MEDIATOR.EFFECT_DATE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setEffectDate(String effectDate) {
        this.effectDate = effectDate == null ? null : effectDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.EXPIRE_DATE
     *
     * @return the value of T_CRM_MEDIATOR.EXPIRE_DATE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.EXPIRE_DATE
     *
     * @param expireDate the value for T_CRM_MEDIATOR.EXPIRE_DATE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate == null ? null : expireDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MEDIATOR.CERT_TYPE
     *
     * @return the value of T_CRM_MEDIATOR.CERT_TYPE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MEDIATOR.CERT_TYPE
     *
     * @param certType the value for T_CRM_MEDIATOR.CERT_TYPE
     *
     * @mbggenerated Fri May 12 09:06:10 CST 2017
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }
}