package com.bohai.dataCenter.entity;

public class CustTrade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUST_TRADE.ID
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUST_TRADE.CUSTNO
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    private String custno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUST_TRADE.CUSTNAME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUST_TRADE.COUNTFEE
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    private String countfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUST_TRADE.VOLUME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUST_TRADE.TURNOVER_VOLUME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    private String turnoverVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUST_TRADE.INSERTTIME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    private String inserttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUST_TRADE.ID
     *
     * @return the value of T_CUST_TRADE.ID
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUST_TRADE.ID
     *
     * @param id the value for T_CUST_TRADE.ID
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUST_TRADE.CUSTNO
     *
     * @return the value of T_CUST_TRADE.CUSTNO
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public String getCustno() {
        return custno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUST_TRADE.CUSTNO
     *
     * @param custno the value for T_CUST_TRADE.CUSTNO
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public void setCustno(String custno) {
        this.custno = custno == null ? null : custno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUST_TRADE.CUSTNAME
     *
     * @return the value of T_CUST_TRADE.CUSTNAME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUST_TRADE.CUSTNAME
     *
     * @param custname the value for T_CUST_TRADE.CUSTNAME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUST_TRADE.COUNTFEE
     *
     * @return the value of T_CUST_TRADE.COUNTFEE
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public String getCountfee() {
        return countfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUST_TRADE.COUNTFEE
     *
     * @param countfee the value for T_CUST_TRADE.COUNTFEE
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public void setCountfee(String countfee) {
        this.countfee = countfee == null ? null : countfee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUST_TRADE.VOLUME
     *
     * @return the value of T_CUST_TRADE.VOLUME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUST_TRADE.VOLUME
     *
     * @param volume the value for T_CUST_TRADE.VOLUME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUST_TRADE.TURNOVER_VOLUME
     *
     * @return the value of T_CUST_TRADE.TURNOVER_VOLUME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public String getTurnoverVolume() {
        return turnoverVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUST_TRADE.TURNOVER_VOLUME
     *
     * @param turnoverVolume the value for T_CUST_TRADE.TURNOVER_VOLUME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public void setTurnoverVolume(String turnoverVolume) {
        this.turnoverVolume = turnoverVolume == null ? null : turnoverVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUST_TRADE.INSERTTIME
     *
     * @return the value of T_CUST_TRADE.INSERTTIME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public String getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUST_TRADE.INSERTTIME
     *
     * @param inserttime the value for T_CUST_TRADE.INSERTTIME
     *
     * @mbggenerated Thu May 25 14:30:06 CST 2017
     */
    public void setInserttime(String inserttime) {
        this.inserttime = inserttime == null ? null : inserttime.trim();
    }
}