package com.bohai.dataCenter.entity;

public class InstrumentAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.INSTRUMENT
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.INSTRUMENT_NAME
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String instrumentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.MULTIPLIER
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String multiplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String exOpenCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String exOpenChargeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String exClosetCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String exClosetChargeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String exCloseyCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String exCloseyChargeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INSTRUMENT_ATTRIBUTE.EXCHANGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    private String exchange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.INSTRUMENT
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.INSTRUMENT
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.INSTRUMENT
     *
     * @param instrument the value for T_INSTRUMENT_ATTRIBUTE.INSTRUMENT
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument == null ? null : instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.INSTRUMENT_NAME
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.INSTRUMENT_NAME
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getInstrumentName() {
        return instrumentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.INSTRUMENT_NAME
     *
     * @param instrumentName the value for T_INSTRUMENT_ATTRIBUTE.INSTRUMENT_NAME
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setInstrumentName(String instrumentName) {
        this.instrumentName = instrumentName == null ? null : instrumentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.MULTIPLIER
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.MULTIPLIER
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getMultiplier() {
        return multiplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.MULTIPLIER
     *
     * @param multiplier the value for T_INSTRUMENT_ATTRIBUTE.MULTIPLIER
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setMultiplier(String multiplier) {
        this.multiplier = multiplier == null ? null : multiplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getExOpenCharge() {
        return exOpenCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE
     *
     * @param exOpenCharge the value for T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setExOpenCharge(String exOpenCharge) {
        this.exOpenCharge = exOpenCharge == null ? null : exOpenCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE_RATE
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getExOpenChargeRate() {
        return exOpenChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE_RATE
     *
     * @param exOpenChargeRate the value for T_INSTRUMENT_ATTRIBUTE.EX_OPEN_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setExOpenChargeRate(String exOpenChargeRate) {
        this.exOpenChargeRate = exOpenChargeRate == null ? null : exOpenChargeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getExClosetCharge() {
        return exClosetCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE
     *
     * @param exClosetCharge the value for T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setExClosetCharge(String exClosetCharge) {
        this.exClosetCharge = exClosetCharge == null ? null : exClosetCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE_RATE
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getExClosetChargeRate() {
        return exClosetChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE_RATE
     *
     * @param exClosetChargeRate the value for T_INSTRUMENT_ATTRIBUTE.EX_CLOSET_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setExClosetChargeRate(String exClosetChargeRate) {
        this.exClosetChargeRate = exClosetChargeRate == null ? null : exClosetChargeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getExCloseyCharge() {
        return exCloseyCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE
     *
     * @param exCloseyCharge the value for T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setExCloseyCharge(String exCloseyCharge) {
        this.exCloseyCharge = exCloseyCharge == null ? null : exCloseyCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE_RATE
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getExCloseyChargeRate() {
        return exCloseyChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE_RATE
     *
     * @param exCloseyChargeRate the value for T_INSTRUMENT_ATTRIBUTE.EX_CLOSEY_CHARGE_RATE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setExCloseyChargeRate(String exCloseyChargeRate) {
        this.exCloseyChargeRate = exCloseyChargeRate == null ? null : exCloseyChargeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INSTRUMENT_ATTRIBUTE.EXCHANGE
     *
     * @return the value of T_INSTRUMENT_ATTRIBUTE.EXCHANGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INSTRUMENT_ATTRIBUTE.EXCHANGE
     *
     * @param exchange the value for T_INSTRUMENT_ATTRIBUTE.EXCHANGE
     *
     * @mbggenerated Thu Apr 13 13:42:59 CST 2017
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }
}