package com.bohai.dataCenter.entity;

public class InvestorCommission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.INVESTOR_NO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.TRADE_DATE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.EXCHANGE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private String exchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.INSTRUMENT_ID
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private String instrumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.OPEN_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short openRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.CLOSE_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short closeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.INDAY_OPEN_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short indayOpenRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.INDAT_CLOSE_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short indatCloseRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.OPEN
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.CLOSE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.INDAY_OPEN
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short indayOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.INDAY_CLOSE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short indayClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.DELIVERY_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short deliveryRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_COMMISSION.DELIVERY
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    private Short delivery;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.INVESTOR_NO
     *
     * @return the value of T_INVESTOR_COMMISSION.INVESTOR_NO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.INVESTOR_NO
     *
     * @param investorNo the value for T_INVESTOR_COMMISSION.INVESTOR_NO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.TRADE_DATE
     *
     * @return the value of T_INVESTOR_COMMISSION.TRADE_DATE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.TRADE_DATE
     *
     * @param tradeDate the value for T_INVESTOR_COMMISSION.TRADE_DATE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.EXCHANGE
     *
     * @return the value of T_INVESTOR_COMMISSION.EXCHANGE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.EXCHANGE
     *
     * @param exchange the value for T_INVESTOR_COMMISSION.EXCHANGE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.INSTRUMENT_ID
     *
     * @return the value of T_INVESTOR_COMMISSION.INSTRUMENT_ID
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public String getInstrumentId() {
        return instrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.INSTRUMENT_ID
     *
     * @param instrumentId the value for T_INVESTOR_COMMISSION.INSTRUMENT_ID
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setInstrumentId(String instrumentId) {
        this.instrumentId = instrumentId == null ? null : instrumentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.OPEN_RATIO
     *
     * @return the value of T_INVESTOR_COMMISSION.OPEN_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getOpenRatio() {
        return openRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.OPEN_RATIO
     *
     * @param openRatio the value for T_INVESTOR_COMMISSION.OPEN_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setOpenRatio(Short openRatio) {
        this.openRatio = openRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.CLOSE_RATIO
     *
     * @return the value of T_INVESTOR_COMMISSION.CLOSE_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getCloseRatio() {
        return closeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.CLOSE_RATIO
     *
     * @param closeRatio the value for T_INVESTOR_COMMISSION.CLOSE_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setCloseRatio(Short closeRatio) {
        this.closeRatio = closeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.INDAY_OPEN_RATIO
     *
     * @return the value of T_INVESTOR_COMMISSION.INDAY_OPEN_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getIndayOpenRatio() {
        return indayOpenRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.INDAY_OPEN_RATIO
     *
     * @param indayOpenRatio the value for T_INVESTOR_COMMISSION.INDAY_OPEN_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setIndayOpenRatio(Short indayOpenRatio) {
        this.indayOpenRatio = indayOpenRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.INDAT_CLOSE_RATIO
     *
     * @return the value of T_INVESTOR_COMMISSION.INDAT_CLOSE_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getIndatCloseRatio() {
        return indatCloseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.INDAT_CLOSE_RATIO
     *
     * @param indatCloseRatio the value for T_INVESTOR_COMMISSION.INDAT_CLOSE_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setIndatCloseRatio(Short indatCloseRatio) {
        this.indatCloseRatio = indatCloseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.OPEN
     *
     * @return the value of T_INVESTOR_COMMISSION.OPEN
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.OPEN
     *
     * @param open the value for T_INVESTOR_COMMISSION.OPEN
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setOpen(Short open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.CLOSE
     *
     * @return the value of T_INVESTOR_COMMISSION.CLOSE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.CLOSE
     *
     * @param close the value for T_INVESTOR_COMMISSION.CLOSE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setClose(Short close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.INDAY_OPEN
     *
     * @return the value of T_INVESTOR_COMMISSION.INDAY_OPEN
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getIndayOpen() {
        return indayOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.INDAY_OPEN
     *
     * @param indayOpen the value for T_INVESTOR_COMMISSION.INDAY_OPEN
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setIndayOpen(Short indayOpen) {
        this.indayOpen = indayOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.INDAY_CLOSE
     *
     * @return the value of T_INVESTOR_COMMISSION.INDAY_CLOSE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getIndayClose() {
        return indayClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.INDAY_CLOSE
     *
     * @param indayClose the value for T_INVESTOR_COMMISSION.INDAY_CLOSE
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setIndayClose(Short indayClose) {
        this.indayClose = indayClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.DELIVERY_RATIO
     *
     * @return the value of T_INVESTOR_COMMISSION.DELIVERY_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getDeliveryRatio() {
        return deliveryRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.DELIVERY_RATIO
     *
     * @param deliveryRatio the value for T_INVESTOR_COMMISSION.DELIVERY_RATIO
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setDeliveryRatio(Short deliveryRatio) {
        this.deliveryRatio = deliveryRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_COMMISSION.DELIVERY
     *
     * @return the value of T_INVESTOR_COMMISSION.DELIVERY
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public Short getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_COMMISSION.DELIVERY
     *
     * @param delivery the value for T_INVESTOR_COMMISSION.DELIVERY
     *
     * @mbggenerated Wed Sep 05 14:37:07 CST 2018
     */
    public void setDelivery(Short delivery) {
        this.delivery = delivery;
    }
}