package com.bohai.dataCenter.entity;

import java.util.Date;

public class MarketerCust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.ID
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.MARKETER_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String marketerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.MARKETER_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String marketerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.CUST_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.CUST_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.CUST_TYPE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.EFFECTIVE_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.EXPIRY_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.REMARK
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.CREATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_CUST.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.ID
     *
     * @return the value of SJZX.T_MARKETER_CUST.ID
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.ID
     *
     * @param id the value for SJZX.T_MARKETER_CUST.ID
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.NO
     *
     * @return the value of SJZX.T_MARKETER_CUST.NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.NO
     *
     * @param no the value for SJZX.T_MARKETER_CUST.NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.MARKETER_NO
     *
     * @return the value of SJZX.T_MARKETER_CUST.MARKETER_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getMarketerNo() {
        return marketerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.MARKETER_NO
     *
     * @param marketerNo the value for SJZX.T_MARKETER_CUST.MARKETER_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setMarketerNo(String marketerNo) {
        this.marketerNo = marketerNo == null ? null : marketerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.MARKETER_NAME
     *
     * @return the value of SJZX.T_MARKETER_CUST.MARKETER_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getMarketerName() {
        return marketerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.MARKETER_NAME
     *
     * @param marketerName the value for SJZX.T_MARKETER_CUST.MARKETER_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setMarketerName(String marketerName) {
        this.marketerName = marketerName == null ? null : marketerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.CUST_NO
     *
     * @return the value of SJZX.T_MARKETER_CUST.CUST_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.CUST_NO
     *
     * @param custNo the value for SJZX.T_MARKETER_CUST.CUST_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.CUST_NAME
     *
     * @return the value of SJZX.T_MARKETER_CUST.CUST_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.CUST_NAME
     *
     * @param custName the value for SJZX.T_MARKETER_CUST.CUST_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.CUST_TYPE
     *
     * @return the value of SJZX.T_MARKETER_CUST.CUST_TYPE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.CUST_TYPE
     *
     * @param custType the value for SJZX.T_MARKETER_CUST.CUST_TYPE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.EFFECTIVE_DATE
     *
     * @return the value of SJZX.T_MARKETER_CUST.EFFECTIVE_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for SJZX.T_MARKETER_CUST.EFFECTIVE_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.EXPIRY_DATE
     *
     * @return the value of SJZX.T_MARKETER_CUST.EXPIRY_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.EXPIRY_DATE
     *
     * @param expiryDate the value for SJZX.T_MARKETER_CUST.EXPIRY_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.REMARK
     *
     * @return the value of SJZX.T_MARKETER_CUST.REMARK
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.REMARK
     *
     * @param remark the value for SJZX.T_MARKETER_CUST.REMARK
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.CREATE_TIME
     *
     * @return the value of SJZX.T_MARKETER_CUST.CREATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.CREATE_TIME
     *
     * @param createTime the value for SJZX.T_MARKETER_CUST.CREATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_CUST.UPDATE_TIME
     *
     * @return the value of SJZX.T_MARKETER_CUST.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_CUST.UPDATE_TIME
     *
     * @param updateTime the value for SJZX.T_MARKETER_CUST.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}