package com.bohai.dataCenter.entity;

import java.util.Date;

public class MarketerMediator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.ID
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.MARKETER_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String marketerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.MARKETER_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String marketerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String mediatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String mediatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.EFFECTIVE_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.EXPIRY_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.REMARK
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.CREATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZX.T_MARKETER_MEDIATOR.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.ID
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.ID
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.ID
     *
     * @param id the value for SJZX.T_MARKETER_MEDIATOR.ID
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.NO
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.NO
     *
     * @param no the value for SJZX.T_MARKETER_MEDIATOR.NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.MARKETER_NO
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.MARKETER_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getMarketerNo() {
        return marketerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.MARKETER_NO
     *
     * @param marketerNo the value for SJZX.T_MARKETER_MEDIATOR.MARKETER_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setMarketerNo(String marketerNo) {
        this.marketerNo = marketerNo == null ? null : marketerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.MARKETER_NAME
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.MARKETER_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getMarketerName() {
        return marketerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.MARKETER_NAME
     *
     * @param marketerName the value for SJZX.T_MARKETER_MEDIATOR.MARKETER_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setMarketerName(String marketerName) {
        this.marketerName = marketerName == null ? null : marketerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NO
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getMediatorNo() {
        return mediatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NO
     *
     * @param mediatorNo the value for SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NO
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setMediatorNo(String mediatorNo) {
        this.mediatorNo = mediatorNo == null ? null : mediatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NAME
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getMediatorName() {
        return mediatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NAME
     *
     * @param mediatorName the value for SJZX.T_MARKETER_MEDIATOR.MEDIATOR_NAME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setMediatorName(String mediatorName) {
        this.mediatorName = mediatorName == null ? null : mediatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.EFFECTIVE_DATE
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.EFFECTIVE_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for SJZX.T_MARKETER_MEDIATOR.EFFECTIVE_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.EXPIRY_DATE
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.EXPIRY_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.EXPIRY_DATE
     *
     * @param expiryDate the value for SJZX.T_MARKETER_MEDIATOR.EXPIRY_DATE
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.REMARK
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.REMARK
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.REMARK
     *
     * @param remark the value for SJZX.T_MARKETER_MEDIATOR.REMARK
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.CREATE_TIME
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.CREATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.CREATE_TIME
     *
     * @param createTime the value for SJZX.T_MARKETER_MEDIATOR.CREATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZX.T_MARKETER_MEDIATOR.UPDATE_TIME
     *
     * @return the value of SJZX.T_MARKETER_MEDIATOR.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZX.T_MARKETER_MEDIATOR.UPDATE_TIME
     *
     * @param updateTime the value for SJZX.T_MARKETER_MEDIATOR.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 30 11:26:42 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}