package com.bohai.dataCenter.entity;

import java.util.Date;

public class MediatorCust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.ID
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.MEDIATOR_NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String mediatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.MEDIATOR_NAME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String mediatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.CUST_NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.CUST_NAME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.ALLOCATION_PROPORTION
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String allocationProportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.EFFECTIVE_DATE
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.EXPIRE_DATE
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private Date expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.REMARK
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.CREATE_TIME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEDIATOR_CUST.UPDATE_TIME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.ID
     *
     * @return the value of T_MEDIATOR_CUST.ID
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.ID
     *
     * @param id the value for T_MEDIATOR_CUST.ID
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.NO
     *
     * @return the value of T_MEDIATOR_CUST.NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.NO
     *
     * @param no the value for T_MEDIATOR_CUST.NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.MEDIATOR_NO
     *
     * @return the value of T_MEDIATOR_CUST.MEDIATOR_NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getMediatorNo() {
        return mediatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.MEDIATOR_NO
     *
     * @param mediatorNo the value for T_MEDIATOR_CUST.MEDIATOR_NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setMediatorNo(String mediatorNo) {
        this.mediatorNo = mediatorNo == null ? null : mediatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.MEDIATOR_NAME
     *
     * @return the value of T_MEDIATOR_CUST.MEDIATOR_NAME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getMediatorName() {
        return mediatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.MEDIATOR_NAME
     *
     * @param mediatorName the value for T_MEDIATOR_CUST.MEDIATOR_NAME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setMediatorName(String mediatorName) {
        this.mediatorName = mediatorName == null ? null : mediatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.CUST_NO
     *
     * @return the value of T_MEDIATOR_CUST.CUST_NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.CUST_NO
     *
     * @param custNo the value for T_MEDIATOR_CUST.CUST_NO
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.CUST_NAME
     *
     * @return the value of T_MEDIATOR_CUST.CUST_NAME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.CUST_NAME
     *
     * @param custName the value for T_MEDIATOR_CUST.CUST_NAME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.ALLOCATION_PROPORTION
     *
     * @return the value of T_MEDIATOR_CUST.ALLOCATION_PROPORTION
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getAllocationProportion() {
        return allocationProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.ALLOCATION_PROPORTION
     *
     * @param allocationProportion the value for T_MEDIATOR_CUST.ALLOCATION_PROPORTION
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setAllocationProportion(String allocationProportion) {
        this.allocationProportion = allocationProportion == null ? null : allocationProportion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.EFFECTIVE_DATE
     *
     * @return the value of T_MEDIATOR_CUST.EFFECTIVE_DATE
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for T_MEDIATOR_CUST.EFFECTIVE_DATE
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.EXPIRE_DATE
     *
     * @return the value of T_MEDIATOR_CUST.EXPIRE_DATE
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.EXPIRE_DATE
     *
     * @param expireDate the value for T_MEDIATOR_CUST.EXPIRE_DATE
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.REMARK
     *
     * @return the value of T_MEDIATOR_CUST.REMARK
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.REMARK
     *
     * @param remark the value for T_MEDIATOR_CUST.REMARK
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.CREATE_TIME
     *
     * @return the value of T_MEDIATOR_CUST.CREATE_TIME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.CREATE_TIME
     *
     * @param createTime the value for T_MEDIATOR_CUST.CREATE_TIME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEDIATOR_CUST.UPDATE_TIME
     *
     * @return the value of T_MEDIATOR_CUST.UPDATE_TIME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEDIATOR_CUST.UPDATE_TIME
     *
     * @param updateTime the value for T_MEDIATOR_CUST.UPDATE_TIME
     *
     * @mbggenerated Fri Mar 31 14:23:30 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}