package com.bohai.dataCenter.entity;

import java.util.Date;

public class RebateList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.ID
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.CATE
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String cate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.CATE_DESP
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String cateDesp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.MARKETER_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String marketerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.MARKETER_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String marketerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.MDEIATOR_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String mdeiatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.MEDIATOR_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String mediatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.INVESTOR_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.INVESTOR_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.REBATE_AMOUNT
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String rebateAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.SPECIAL_CATE
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String specialCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.SPECIAL_DESP
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String specialDesp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.REMARK
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.FIX_PROPORTION
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String fixProportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.DAILY_RIGHTS
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String dailyRights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.CUSTOM_INTERVAL
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String customInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.CREATE_TIME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REBATE_LIST.CREATE_BY
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    private String createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.ID
     *
     * @return the value of T_REBATE_LIST.ID
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.ID
     *
     * @param id the value for T_REBATE_LIST.ID
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.CATE
     *
     * @return the value of T_REBATE_LIST.CATE
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getCate() {
        return cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.CATE
     *
     * @param cate the value for T_REBATE_LIST.CATE
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setCate(String cate) {
        this.cate = cate == null ? null : cate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.CATE_DESP
     *
     * @return the value of T_REBATE_LIST.CATE_DESP
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getCateDesp() {
        return cateDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.CATE_DESP
     *
     * @param cateDesp the value for T_REBATE_LIST.CATE_DESP
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setCateDesp(String cateDesp) {
        this.cateDesp = cateDesp == null ? null : cateDesp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.MARKETER_NO
     *
     * @return the value of T_REBATE_LIST.MARKETER_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getMarketerNo() {
        return marketerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.MARKETER_NO
     *
     * @param marketerNo the value for T_REBATE_LIST.MARKETER_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setMarketerNo(String marketerNo) {
        this.marketerNo = marketerNo == null ? null : marketerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.MARKETER_NAME
     *
     * @return the value of T_REBATE_LIST.MARKETER_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getMarketerName() {
        return marketerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.MARKETER_NAME
     *
     * @param marketerName the value for T_REBATE_LIST.MARKETER_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setMarketerName(String marketerName) {
        this.marketerName = marketerName == null ? null : marketerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.MDEIATOR_NO
     *
     * @return the value of T_REBATE_LIST.MDEIATOR_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getMdeiatorNo() {
        return mdeiatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.MDEIATOR_NO
     *
     * @param mdeiatorNo the value for T_REBATE_LIST.MDEIATOR_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setMdeiatorNo(String mdeiatorNo) {
        this.mdeiatorNo = mdeiatorNo == null ? null : mdeiatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.MEDIATOR_NAME
     *
     * @return the value of T_REBATE_LIST.MEDIATOR_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getMediatorName() {
        return mediatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.MEDIATOR_NAME
     *
     * @param mediatorName the value for T_REBATE_LIST.MEDIATOR_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setMediatorName(String mediatorName) {
        this.mediatorName = mediatorName == null ? null : mediatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.INVESTOR_NO
     *
     * @return the value of T_REBATE_LIST.INVESTOR_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.INVESTOR_NO
     *
     * @param investorNo the value for T_REBATE_LIST.INVESTOR_NO
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.INVESTOR_NAME
     *
     * @return the value of T_REBATE_LIST.INVESTOR_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.INVESTOR_NAME
     *
     * @param investorName the value for T_REBATE_LIST.INVESTOR_NAME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName == null ? null : investorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.REBATE_AMOUNT
     *
     * @return the value of T_REBATE_LIST.REBATE_AMOUNT
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getRebateAmount() {
        return rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.REBATE_AMOUNT
     *
     * @param rebateAmount the value for T_REBATE_LIST.REBATE_AMOUNT
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setRebateAmount(String rebateAmount) {
        this.rebateAmount = rebateAmount == null ? null : rebateAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.SPECIAL_CATE
     *
     * @return the value of T_REBATE_LIST.SPECIAL_CATE
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getSpecialCate() {
        return specialCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.SPECIAL_CATE
     *
     * @param specialCate the value for T_REBATE_LIST.SPECIAL_CATE
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setSpecialCate(String specialCate) {
        this.specialCate = specialCate == null ? null : specialCate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.SPECIAL_DESP
     *
     * @return the value of T_REBATE_LIST.SPECIAL_DESP
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getSpecialDesp() {
        return specialDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.SPECIAL_DESP
     *
     * @param specialDesp the value for T_REBATE_LIST.SPECIAL_DESP
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setSpecialDesp(String specialDesp) {
        this.specialDesp = specialDesp == null ? null : specialDesp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.REMARK
     *
     * @return the value of T_REBATE_LIST.REMARK
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.REMARK
     *
     * @param remark the value for T_REBATE_LIST.REMARK
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.FIX_PROPORTION
     *
     * @return the value of T_REBATE_LIST.FIX_PROPORTION
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getFixProportion() {
        return fixProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.FIX_PROPORTION
     *
     * @param fixProportion the value for T_REBATE_LIST.FIX_PROPORTION
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setFixProportion(String fixProportion) {
        this.fixProportion = fixProportion == null ? null : fixProportion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.DAILY_RIGHTS
     *
     * @return the value of T_REBATE_LIST.DAILY_RIGHTS
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getDailyRights() {
        return dailyRights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.DAILY_RIGHTS
     *
     * @param dailyRights the value for T_REBATE_LIST.DAILY_RIGHTS
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setDailyRights(String dailyRights) {
        this.dailyRights = dailyRights == null ? null : dailyRights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.CUSTOM_INTERVAL
     *
     * @return the value of T_REBATE_LIST.CUSTOM_INTERVAL
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getCustomInterval() {
        return customInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.CUSTOM_INTERVAL
     *
     * @param customInterval the value for T_REBATE_LIST.CUSTOM_INTERVAL
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setCustomInterval(String customInterval) {
        this.customInterval = customInterval == null ? null : customInterval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.CREATE_TIME
     *
     * @return the value of T_REBATE_LIST.CREATE_TIME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.CREATE_TIME
     *
     * @param createTime the value for T_REBATE_LIST.CREATE_TIME
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REBATE_LIST.CREATE_BY
     *
     * @return the value of T_REBATE_LIST.CREATE_BY
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REBATE_LIST.CREATE_BY
     *
     * @param createBy the value for T_REBATE_LIST.CREATE_BY
     *
     * @mbggenerated Fri Apr 07 09:45:35 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }
}