package com.bohai.dataCenter.entity;

import java.util.Date;

public class ReportMarketerInterest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.ID
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.INVESTOR_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.INVESTOR_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.DEPT_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.FIX_PROPORTION
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String fixProportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.DAILY_RIGHTS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String dailyRights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.INTEREST_AMOUNT
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String interestAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.TRADE_DATE_STR
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String tradeDateStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.TRADE_DATE
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private Date tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.DATE_TYPE
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String dateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.CREATE_TIME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.CREATE_BY
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.AVAILABLE_FUNDS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String availableFunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.RIGHTS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String rights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.UPDATE_TIME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.UPDATE_BY
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.MEDIATOR_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String mediatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.MEDIATOR_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String mediatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.MARKET_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String marketNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_MARKETER_INTEREST.MARKET_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    private String marketName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.ID
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.ID
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.ID
     *
     * @param id the value for T_REPORT_MARKETER_INTEREST.ID
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.INVESTOR_NO
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.INVESTOR_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.INVESTOR_NO
     *
     * @param investorNo the value for T_REPORT_MARKETER_INTEREST.INVESTOR_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.INVESTOR_NAME
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.INVESTOR_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.INVESTOR_NAME
     *
     * @param investorName the value for T_REPORT_MARKETER_INTEREST.INVESTOR_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName == null ? null : investorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.DEPT_NAME
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.DEPT_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.DEPT_NAME
     *
     * @param deptName the value for T_REPORT_MARKETER_INTEREST.DEPT_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.FIX_PROPORTION
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.FIX_PROPORTION
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getFixProportion() {
        return fixProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.FIX_PROPORTION
     *
     * @param fixProportion the value for T_REPORT_MARKETER_INTEREST.FIX_PROPORTION
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setFixProportion(String fixProportion) {
        this.fixProportion = fixProportion == null ? null : fixProportion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.DAILY_RIGHTS
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.DAILY_RIGHTS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getDailyRights() {
        return dailyRights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.DAILY_RIGHTS
     *
     * @param dailyRights the value for T_REPORT_MARKETER_INTEREST.DAILY_RIGHTS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setDailyRights(String dailyRights) {
        this.dailyRights = dailyRights == null ? null : dailyRights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.INTEREST_AMOUNT
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.INTEREST_AMOUNT
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getInterestAmount() {
        return interestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.INTEREST_AMOUNT
     *
     * @param interestAmount the value for T_REPORT_MARKETER_INTEREST.INTEREST_AMOUNT
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setInterestAmount(String interestAmount) {
        this.interestAmount = interestAmount == null ? null : interestAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.TRADE_DATE_STR
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.TRADE_DATE_STR
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getTradeDateStr() {
        return tradeDateStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.TRADE_DATE_STR
     *
     * @param tradeDateStr the value for T_REPORT_MARKETER_INTEREST.TRADE_DATE_STR
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setTradeDateStr(String tradeDateStr) {
        this.tradeDateStr = tradeDateStr == null ? null : tradeDateStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.TRADE_DATE
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.TRADE_DATE
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public Date getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.TRADE_DATE
     *
     * @param tradeDate the value for T_REPORT_MARKETER_INTEREST.TRADE_DATE
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.DATE_TYPE
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.DATE_TYPE
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.DATE_TYPE
     *
     * @param dateType the value for T_REPORT_MARKETER_INTEREST.DATE_TYPE
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setDateType(String dateType) {
        this.dateType = dateType == null ? null : dateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.CREATE_TIME
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.CREATE_TIME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.CREATE_TIME
     *
     * @param createTime the value for T_REPORT_MARKETER_INTEREST.CREATE_TIME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.CREATE_BY
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.CREATE_BY
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.CREATE_BY
     *
     * @param createBy the value for T_REPORT_MARKETER_INTEREST.CREATE_BY
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.AVAILABLE_FUNDS
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.AVAILABLE_FUNDS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getAvailableFunds() {
        return availableFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.AVAILABLE_FUNDS
     *
     * @param availableFunds the value for T_REPORT_MARKETER_INTEREST.AVAILABLE_FUNDS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setAvailableFunds(String availableFunds) {
        this.availableFunds = availableFunds == null ? null : availableFunds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.RIGHTS
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.RIGHTS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.RIGHTS
     *
     * @param rights the value for T_REPORT_MARKETER_INTEREST.RIGHTS
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.UPDATE_TIME
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.UPDATE_TIME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.UPDATE_TIME
     *
     * @param updateTime the value for T_REPORT_MARKETER_INTEREST.UPDATE_TIME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.UPDATE_BY
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.UPDATE_BY
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.UPDATE_BY
     *
     * @param updateBy the value for T_REPORT_MARKETER_INTEREST.UPDATE_BY
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.MEDIATOR_NO
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.MEDIATOR_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getMediatorNo() {
        return mediatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.MEDIATOR_NO
     *
     * @param mediatorNo the value for T_REPORT_MARKETER_INTEREST.MEDIATOR_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setMediatorNo(String mediatorNo) {
        this.mediatorNo = mediatorNo == null ? null : mediatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.MEDIATOR_NAME
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.MEDIATOR_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getMediatorName() {
        return mediatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.MEDIATOR_NAME
     *
     * @param mediatorName the value for T_REPORT_MARKETER_INTEREST.MEDIATOR_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setMediatorName(String mediatorName) {
        this.mediatorName = mediatorName == null ? null : mediatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.MARKET_NO
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.MARKET_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getMarketNo() {
        return marketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.MARKET_NO
     *
     * @param marketNo the value for T_REPORT_MARKETER_INTEREST.MARKET_NO
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setMarketNo(String marketNo) {
        this.marketNo = marketNo == null ? null : marketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_MARKETER_INTEREST.MARKET_NAME
     *
     * @return the value of T_REPORT_MARKETER_INTEREST.MARKET_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public String getMarketName() {
        return marketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_MARKETER_INTEREST.MARKET_NAME
     *
     * @param marketName the value for T_REPORT_MARKETER_INTEREST.MARKET_NAME
     *
     * @mbggenerated Wed May 24 14:29:55 CST 2017
     */
    public void setMarketName(String marketName) {
        this.marketName = marketName == null ? null : marketName.trim();
    }
}