package com.bohai.dataCenter.entity;

import java.util.Date;

public class ReportExchangeRebate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.MONTH
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.DEP_NAME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.DEP_CODE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.SREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private String srebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.ZREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private String zrebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.JREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private String jrebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.DREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private String drebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.CREATE_TIME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_REPORT_EXCHANGE_REBATE.UPDATE_TIME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.MONTH
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.MONTH
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.MONTH
     *
     * @param month the value for T_REPORT_EXCHANGE_REBATE.MONTH
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.DEP_NAME
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.DEP_NAME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.DEP_NAME
     *
     * @param depName the value for T_REPORT_EXCHANGE_REBATE.DEP_NAME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.DEP_CODE
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.DEP_CODE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.DEP_CODE
     *
     * @param depCode the value for T_REPORT_EXCHANGE_REBATE.DEP_CODE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.SREBATE
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.SREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public String getSrebate() {
        return srebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.SREBATE
     *
     * @param srebate the value for T_REPORT_EXCHANGE_REBATE.SREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setSrebate(String srebate) {
        this.srebate = srebate == null ? null : srebate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.ZREBATE
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.ZREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public String getZrebate() {
        return zrebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.ZREBATE
     *
     * @param zrebate the value for T_REPORT_EXCHANGE_REBATE.ZREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setZrebate(String zrebate) {
        this.zrebate = zrebate == null ? null : zrebate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.JREBATE
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.JREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public String getJrebate() {
        return jrebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.JREBATE
     *
     * @param jrebate the value for T_REPORT_EXCHANGE_REBATE.JREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setJrebate(String jrebate) {
        this.jrebate = jrebate == null ? null : jrebate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.DREBATE
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.DREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public String getDrebate() {
        return drebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.DREBATE
     *
     * @param drebate the value for T_REPORT_EXCHANGE_REBATE.DREBATE
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setDrebate(String drebate) {
        this.drebate = drebate == null ? null : drebate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.CREATE_TIME
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.CREATE_TIME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.CREATE_TIME
     *
     * @param createTime the value for T_REPORT_EXCHANGE_REBATE.CREATE_TIME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_REPORT_EXCHANGE_REBATE.UPDATE_TIME
     *
     * @return the value of T_REPORT_EXCHANGE_REBATE.UPDATE_TIME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_REPORT_EXCHANGE_REBATE.UPDATE_TIME
     *
     * @param updateTime the value for T_REPORT_EXCHANGE_REBATE.UPDATE_TIME
     *
     * @mbggenerated Wed Apr 19 12:09:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}