package com.bohai.dataCenter.entity;

import java.util.Date;

public class SysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.permission
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.permission_level
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String permissionLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.parent_permission_id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private Long parentPermissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.description
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.available
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.url
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.create_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.update_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private Date updateTime;
    
    //逻辑字段
    private String hasPermission;
    

    public String getHasPermission() {
        return hasPermission;
    }

    public void setHasPermission(String hasPermission) {
        this.hasPermission = hasPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.id
     *
     * @return the value of sys_permissions.id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.id
     *
     * @param id the value for sys_permissions.id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.permission
     *
     * @return the value of sys_permissions.permission
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.permission
     *
     * @param permission the value for sys_permissions.permission
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.permission_level
     *
     * @return the value of sys_permissions.permission_level
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getPermissionLevel() {
        return permissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.permission_level
     *
     * @param permissionLevel the value for sys_permissions.permission_level
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setPermissionLevel(String permissionLevel) {
        this.permissionLevel = permissionLevel == null ? null : permissionLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.parent_permission_id
     *
     * @return the value of sys_permissions.parent_permission_id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public Long getParentPermissionId() {
        return parentPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.parent_permission_id
     *
     * @param parentPermissionId the value for sys_permissions.parent_permission_id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setParentPermissionId(Long parentPermissionId) {
        this.parentPermissionId = parentPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.description
     *
     * @return the value of sys_permissions.description
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.description
     *
     * @param description the value for sys_permissions.description
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.available
     *
     * @return the value of sys_permissions.available
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.available
     *
     * @param available the value for sys_permissions.available
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.url
     *
     * @return the value of sys_permissions.url
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.url
     *
     * @param url the value for sys_permissions.url
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.create_time
     *
     * @return the value of sys_permissions.create_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.create_time
     *
     * @param createTime the value for sys_permissions.create_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.update_time
     *
     * @return the value of sys_permissions.update_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.update_time
     *
     * @param updateTime the value for sys_permissions.update_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}