package com.bohai.dataCenter.entity;

import java.util.Date;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.role
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.description
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.available
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private String available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.create_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.update_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.id
     *
     * @return the value of sys_roles.id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.id
     *
     * @param id the value for sys_roles.id
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.role
     *
     * @return the value of sys_roles.role
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.role
     *
     * @param role the value for sys_roles.role
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.description
     *
     * @return the value of sys_roles.description
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.description
     *
     * @param description the value for sys_roles.description
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.available
     *
     * @return the value of sys_roles.available
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.available
     *
     * @param available the value for sys_roles.available
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.create_time
     *
     * @return the value of sys_roles.create_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.create_time
     *
     * @param createTime the value for sys_roles.create_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.update_time
     *
     * @return the value of sys_roles.update_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.update_time
     *
     * @param updateTime the value for sys_roles.update_time
     *
     * @mbggenerated Mon Dec 12 08:56:50 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}