package com.bohai.dataCenter.entity;

import java.math.BigDecimal;

public class TradeData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.SERIAL_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.DAY
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.TRADE_DATE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.TRADE_TIME
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.INVESTOR_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.INSTRUMENT
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.DIRECTION
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.VOLUME
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private Long volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.DEAL_PRICE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private BigDecimal dealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.TURNOVER
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private BigDecimal turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.OFFSET_FLAG
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String offsetFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.HADGE_FLAG
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String hadgeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.DAILY_MARKET_WIN
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private BigDecimal dailyMarketWin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.HEDGE_WIN
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private BigDecimal hedgeWin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.CHARGE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private BigDecimal charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.TRADE_CODE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String tradeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.EXCHANGE_ID
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String exchangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.IS_MEMBER
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String isMember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.ORDER_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.SEAT_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String seatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_DATA.CURRENCY
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    private String currency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.SERIAL_NO
     *
     * @return the value of T_TRADE_DATA.SERIAL_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.SERIAL_NO
     *
     * @param serialNo the value for T_TRADE_DATA.SERIAL_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.DAY
     *
     * @return the value of T_TRADE_DATA.DAY
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.DAY
     *
     * @param day the value for T_TRADE_DATA.DAY
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.TRADE_DATE
     *
     * @return the value of T_TRADE_DATA.TRADE_DATE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.TRADE_DATE
     *
     * @param tradeDate the value for T_TRADE_DATA.TRADE_DATE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.TRADE_TIME
     *
     * @return the value of T_TRADE_DATA.TRADE_TIME
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.TRADE_TIME
     *
     * @param tradeTime the value for T_TRADE_DATA.TRADE_TIME
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setTradeTime(String tradeTime) {
        this.tradeTime = tradeTime == null ? null : tradeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.INVESTOR_NO
     *
     * @return the value of T_TRADE_DATA.INVESTOR_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.INVESTOR_NO
     *
     * @param investorNo the value for T_TRADE_DATA.INVESTOR_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.INSTRUMENT
     *
     * @return the value of T_TRADE_DATA.INSTRUMENT
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.INSTRUMENT
     *
     * @param instrument the value for T_TRADE_DATA.INSTRUMENT
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument == null ? null : instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.DIRECTION
     *
     * @return the value of T_TRADE_DATA.DIRECTION
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.DIRECTION
     *
     * @param direction the value for T_TRADE_DATA.DIRECTION
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.VOLUME
     *
     * @return the value of T_TRADE_DATA.VOLUME
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.VOLUME
     *
     * @param volume the value for T_TRADE_DATA.VOLUME
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.DEAL_PRICE
     *
     * @return the value of T_TRADE_DATA.DEAL_PRICE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public BigDecimal getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.DEAL_PRICE
     *
     * @param dealPrice the value for T_TRADE_DATA.DEAL_PRICE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setDealPrice(BigDecimal dealPrice) {
        this.dealPrice = dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.TURNOVER
     *
     * @return the value of T_TRADE_DATA.TURNOVER
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public BigDecimal getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.TURNOVER
     *
     * @param turnover the value for T_TRADE_DATA.TURNOVER
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setTurnover(BigDecimal turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.OFFSET_FLAG
     *
     * @return the value of T_TRADE_DATA.OFFSET_FLAG
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getOffsetFlag() {
        return offsetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.OFFSET_FLAG
     *
     * @param offsetFlag the value for T_TRADE_DATA.OFFSET_FLAG
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setOffsetFlag(String offsetFlag) {
        this.offsetFlag = offsetFlag == null ? null : offsetFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.HADGE_FLAG
     *
     * @return the value of T_TRADE_DATA.HADGE_FLAG
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getHadgeFlag() {
        return hadgeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.HADGE_FLAG
     *
     * @param hadgeFlag the value for T_TRADE_DATA.HADGE_FLAG
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setHadgeFlag(String hadgeFlag) {
        this.hadgeFlag = hadgeFlag == null ? null : hadgeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.DAILY_MARKET_WIN
     *
     * @return the value of T_TRADE_DATA.DAILY_MARKET_WIN
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public BigDecimal getDailyMarketWin() {
        return dailyMarketWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.DAILY_MARKET_WIN
     *
     * @param dailyMarketWin the value for T_TRADE_DATA.DAILY_MARKET_WIN
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setDailyMarketWin(BigDecimal dailyMarketWin) {
        this.dailyMarketWin = dailyMarketWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.HEDGE_WIN
     *
     * @return the value of T_TRADE_DATA.HEDGE_WIN
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public BigDecimal getHedgeWin() {
        return hedgeWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.HEDGE_WIN
     *
     * @param hedgeWin the value for T_TRADE_DATA.HEDGE_WIN
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setHedgeWin(BigDecimal hedgeWin) {
        this.hedgeWin = hedgeWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.CHARGE
     *
     * @return the value of T_TRADE_DATA.CHARGE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.CHARGE
     *
     * @param charge the value for T_TRADE_DATA.CHARGE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.TRADE_CODE
     *
     * @return the value of T_TRADE_DATA.TRADE_CODE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getTradeCode() {
        return tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.TRADE_CODE
     *
     * @param tradeCode the value for T_TRADE_DATA.TRADE_CODE
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setTradeCode(String tradeCode) {
        this.tradeCode = tradeCode == null ? null : tradeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.EXCHANGE_ID
     *
     * @return the value of T_TRADE_DATA.EXCHANGE_ID
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getExchangeId() {
        return exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.EXCHANGE_ID
     *
     * @param exchangeId the value for T_TRADE_DATA.EXCHANGE_ID
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setExchangeId(String exchangeId) {
        this.exchangeId = exchangeId == null ? null : exchangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.IS_MEMBER
     *
     * @return the value of T_TRADE_DATA.IS_MEMBER
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getIsMember() {
        return isMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.IS_MEMBER
     *
     * @param isMember the value for T_TRADE_DATA.IS_MEMBER
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setIsMember(String isMember) {
        this.isMember = isMember == null ? null : isMember.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.ORDER_NO
     *
     * @return the value of T_TRADE_DATA.ORDER_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.ORDER_NO
     *
     * @param orderNo the value for T_TRADE_DATA.ORDER_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.SEAT_NO
     *
     * @return the value of T_TRADE_DATA.SEAT_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getSeatNo() {
        return seatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.SEAT_NO
     *
     * @param seatNo the value for T_TRADE_DATA.SEAT_NO
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo == null ? null : seatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_DATA.CURRENCY
     *
     * @return the value of T_TRADE_DATA.CURRENCY
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_DATA.CURRENCY
     *
     * @param currency the value for T_TRADE_DATA.CURRENCY
     *
     * @mbggenerated Thu Apr 13 09:57:09 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }
}