package com.bohai.dataCenter.entity;

import java.util.Date;

public class TransactionStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.ID
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.TRADE_DATE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.INVESTOR_NO
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.INVESTOR_NAME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.INVESTOR_TYPE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String investorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.CURRENCY
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.EXCHANGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String exchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.INSTRUMENT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.PRODUCT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.DELIVERY_PERIOD
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String deliveryPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.TRADE_TYPE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.ONHAND_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String onhandCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.RETENTION_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String retentionCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.TOTAL_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String totalVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.PLATFORM_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String platformVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.CLOSE_TODAY_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String closeTodayVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.PLATFORM_CHARGE_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String platformChargeVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.PLATFORM_FREE_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String platformFreeVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.TURNOVER
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.CLOSE_TODAY_TURNOVER
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String closeTodayTurnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.CLOSE_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String closeProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.POSITION_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String positionProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.NET_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String netProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String deliveryCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.ONHAND_DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String onhandDeliveryCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.RETAINED_DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String retainedDeliveryCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.DELIVERY_QUANTITY
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String deliveryQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.BUY_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String buyVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.SELL_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String sellVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.INVESTOR_MARGIN
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String investorMargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.EXCHANGE_MARGIN
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String exchangeMargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.LONG_OPTION_VALUE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String longOptionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.SHORT_OPTION_VALUE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String shortOptionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.ROYALTY_INCOME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String royaltyIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.ROYALTY_PAYMENT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String royaltyPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.EXCHANGE_EXERCISE_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String exchangeExerciseCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.EXERCISE_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String exerciseCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.EXERCISE_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String exerciseProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.BATCH_NO
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.CREATE_TIME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRANSACTION_STATISTICS.UPDATE_TIME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.ID
     *
     * @return the value of T_TRANSACTION_STATISTICS.ID
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.ID
     *
     * @param id the value for T_TRANSACTION_STATISTICS.ID
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.TRADE_DATE
     *
     * @return the value of T_TRANSACTION_STATISTICS.TRADE_DATE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.TRADE_DATE
     *
     * @param tradeDate the value for T_TRANSACTION_STATISTICS.TRADE_DATE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_NO
     *
     * @return the value of T_TRANSACTION_STATISTICS.INVESTOR_NO
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_NO
     *
     * @param investorNo the value for T_TRANSACTION_STATISTICS.INVESTOR_NO
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_NAME
     *
     * @return the value of T_TRANSACTION_STATISTICS.INVESTOR_NAME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_NAME
     *
     * @param investorName the value for T_TRANSACTION_STATISTICS.INVESTOR_NAME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName == null ? null : investorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_TYPE
     *
     * @return the value of T_TRANSACTION_STATISTICS.INVESTOR_TYPE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getInvestorType() {
        return investorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_TYPE
     *
     * @param investorType the value for T_TRANSACTION_STATISTICS.INVESTOR_TYPE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setInvestorType(String investorType) {
        this.investorType = investorType == null ? null : investorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.CURRENCY
     *
     * @return the value of T_TRANSACTION_STATISTICS.CURRENCY
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.CURRENCY
     *
     * @param currency the value for T_TRANSACTION_STATISTICS.CURRENCY
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.EXCHANGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.EXCHANGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.EXCHANGE
     *
     * @param exchange the value for T_TRANSACTION_STATISTICS.EXCHANGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.INSTRUMENT
     *
     * @return the value of T_TRANSACTION_STATISTICS.INSTRUMENT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.INSTRUMENT
     *
     * @param instrument the value for T_TRANSACTION_STATISTICS.INSTRUMENT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument == null ? null : instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.PRODUCT
     *
     * @return the value of T_TRANSACTION_STATISTICS.PRODUCT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.PRODUCT
     *
     * @param product the value for T_TRANSACTION_STATISTICS.PRODUCT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.DELIVERY_PERIOD
     *
     * @return the value of T_TRANSACTION_STATISTICS.DELIVERY_PERIOD
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getDeliveryPeriod() {
        return deliveryPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.DELIVERY_PERIOD
     *
     * @param deliveryPeriod the value for T_TRANSACTION_STATISTICS.DELIVERY_PERIOD
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setDeliveryPeriod(String deliveryPeriod) {
        this.deliveryPeriod = deliveryPeriod == null ? null : deliveryPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.TRADE_TYPE
     *
     * @return the value of T_TRANSACTION_STATISTICS.TRADE_TYPE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.TRADE_TYPE
     *
     * @param tradeType the value for T_TRANSACTION_STATISTICS.TRADE_TYPE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.CHARGE
     *
     * @param charge the value for T_TRANSACTION_STATISTICS.CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setCharge(String charge) {
        this.charge = charge == null ? null : charge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.ONHAND_CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.ONHAND_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getOnhandCharge() {
        return onhandCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.ONHAND_CHARGE
     *
     * @param onhandCharge the value for T_TRANSACTION_STATISTICS.ONHAND_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setOnhandCharge(String onhandCharge) {
        this.onhandCharge = onhandCharge == null ? null : onhandCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.RETENTION_CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.RETENTION_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getRetentionCharge() {
        return retentionCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.RETENTION_CHARGE
     *
     * @param retentionCharge the value for T_TRANSACTION_STATISTICS.RETENTION_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setRetentionCharge(String retentionCharge) {
        this.retentionCharge = retentionCharge == null ? null : retentionCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.PROFIT
     *
     * @return the value of T_TRANSACTION_STATISTICS.PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.PROFIT
     *
     * @param profit the value for T_TRANSACTION_STATISTICS.PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setProfit(String profit) {
        this.profit = profit == null ? null : profit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.TOTAL_VOLUME
     *
     * @return the value of T_TRANSACTION_STATISTICS.TOTAL_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getTotalVolume() {
        return totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.TOTAL_VOLUME
     *
     * @param totalVolume the value for T_TRANSACTION_STATISTICS.TOTAL_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setTotalVolume(String totalVolume) {
        this.totalVolume = totalVolume == null ? null : totalVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.PLATFORM_VOLUME
     *
     * @return the value of T_TRANSACTION_STATISTICS.PLATFORM_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getPlatformVolume() {
        return platformVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.PLATFORM_VOLUME
     *
     * @param platformVolume the value for T_TRANSACTION_STATISTICS.PLATFORM_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setPlatformVolume(String platformVolume) {
        this.platformVolume = platformVolume == null ? null : platformVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.CLOSE_TODAY_VOLUME
     *
     * @return the value of T_TRANSACTION_STATISTICS.CLOSE_TODAY_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getCloseTodayVolume() {
        return closeTodayVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.CLOSE_TODAY_VOLUME
     *
     * @param closeTodayVolume the value for T_TRANSACTION_STATISTICS.CLOSE_TODAY_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setCloseTodayVolume(String closeTodayVolume) {
        this.closeTodayVolume = closeTodayVolume == null ? null : closeTodayVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.PLATFORM_CHARGE_VOLUME
     *
     * @return the value of T_TRANSACTION_STATISTICS.PLATFORM_CHARGE_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getPlatformChargeVolume() {
        return platformChargeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.PLATFORM_CHARGE_VOLUME
     *
     * @param platformChargeVolume the value for T_TRANSACTION_STATISTICS.PLATFORM_CHARGE_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setPlatformChargeVolume(String platformChargeVolume) {
        this.platformChargeVolume = platformChargeVolume == null ? null : platformChargeVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.PLATFORM_FREE_VOLUME
     *
     * @return the value of T_TRANSACTION_STATISTICS.PLATFORM_FREE_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getPlatformFreeVolume() {
        return platformFreeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.PLATFORM_FREE_VOLUME
     *
     * @param platformFreeVolume the value for T_TRANSACTION_STATISTICS.PLATFORM_FREE_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setPlatformFreeVolume(String platformFreeVolume) {
        this.platformFreeVolume = platformFreeVolume == null ? null : platformFreeVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.TURNOVER
     *
     * @return the value of T_TRANSACTION_STATISTICS.TURNOVER
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.TURNOVER
     *
     * @param turnover the value for T_TRANSACTION_STATISTICS.TURNOVER
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setTurnover(String turnover) {
        this.turnover = turnover == null ? null : turnover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.CLOSE_TODAY_TURNOVER
     *
     * @return the value of T_TRANSACTION_STATISTICS.CLOSE_TODAY_TURNOVER
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getCloseTodayTurnover() {
        return closeTodayTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.CLOSE_TODAY_TURNOVER
     *
     * @param closeTodayTurnover the value for T_TRANSACTION_STATISTICS.CLOSE_TODAY_TURNOVER
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setCloseTodayTurnover(String closeTodayTurnover) {
        this.closeTodayTurnover = closeTodayTurnover == null ? null : closeTodayTurnover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.CLOSE_PROFIT
     *
     * @return the value of T_TRANSACTION_STATISTICS.CLOSE_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getCloseProfit() {
        return closeProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.CLOSE_PROFIT
     *
     * @param closeProfit the value for T_TRANSACTION_STATISTICS.CLOSE_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setCloseProfit(String closeProfit) {
        this.closeProfit = closeProfit == null ? null : closeProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.POSITION_PROFIT
     *
     * @return the value of T_TRANSACTION_STATISTICS.POSITION_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getPositionProfit() {
        return positionProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.POSITION_PROFIT
     *
     * @param positionProfit the value for T_TRANSACTION_STATISTICS.POSITION_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setPositionProfit(String positionProfit) {
        this.positionProfit = positionProfit == null ? null : positionProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.NET_PROFIT
     *
     * @return the value of T_TRANSACTION_STATISTICS.NET_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getNetProfit() {
        return netProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.NET_PROFIT
     *
     * @param netProfit the value for T_TRANSACTION_STATISTICS.NET_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setNetProfit(String netProfit) {
        this.netProfit = netProfit == null ? null : netProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.DELIVERY_CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getDeliveryCharge() {
        return deliveryCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.DELIVERY_CHARGE
     *
     * @param deliveryCharge the value for T_TRANSACTION_STATISTICS.DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setDeliveryCharge(String deliveryCharge) {
        this.deliveryCharge = deliveryCharge == null ? null : deliveryCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.ONHAND_DELIVERY_CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.ONHAND_DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getOnhandDeliveryCharge() {
        return onhandDeliveryCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.ONHAND_DELIVERY_CHARGE
     *
     * @param onhandDeliveryCharge the value for T_TRANSACTION_STATISTICS.ONHAND_DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setOnhandDeliveryCharge(String onhandDeliveryCharge) {
        this.onhandDeliveryCharge = onhandDeliveryCharge == null ? null : onhandDeliveryCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.RETAINED_DELIVERY_CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.RETAINED_DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getRetainedDeliveryCharge() {
        return retainedDeliveryCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.RETAINED_DELIVERY_CHARGE
     *
     * @param retainedDeliveryCharge the value for T_TRANSACTION_STATISTICS.RETAINED_DELIVERY_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setRetainedDeliveryCharge(String retainedDeliveryCharge) {
        this.retainedDeliveryCharge = retainedDeliveryCharge == null ? null : retainedDeliveryCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.DELIVERY_QUANTITY
     *
     * @return the value of T_TRANSACTION_STATISTICS.DELIVERY_QUANTITY
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getDeliveryQuantity() {
        return deliveryQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.DELIVERY_QUANTITY
     *
     * @param deliveryQuantity the value for T_TRANSACTION_STATISTICS.DELIVERY_QUANTITY
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setDeliveryQuantity(String deliveryQuantity) {
        this.deliveryQuantity = deliveryQuantity == null ? null : deliveryQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.BUY_VOLUME
     *
     * @return the value of T_TRANSACTION_STATISTICS.BUY_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getBuyVolume() {
        return buyVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.BUY_VOLUME
     *
     * @param buyVolume the value for T_TRANSACTION_STATISTICS.BUY_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setBuyVolume(String buyVolume) {
        this.buyVolume = buyVolume == null ? null : buyVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.SELL_VOLUME
     *
     * @return the value of T_TRANSACTION_STATISTICS.SELL_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getSellVolume() {
        return sellVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.SELL_VOLUME
     *
     * @param sellVolume the value for T_TRANSACTION_STATISTICS.SELL_VOLUME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setSellVolume(String sellVolume) {
        this.sellVolume = sellVolume == null ? null : sellVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_MARGIN
     *
     * @return the value of T_TRANSACTION_STATISTICS.INVESTOR_MARGIN
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getInvestorMargin() {
        return investorMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.INVESTOR_MARGIN
     *
     * @param investorMargin the value for T_TRANSACTION_STATISTICS.INVESTOR_MARGIN
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setInvestorMargin(String investorMargin) {
        this.investorMargin = investorMargin == null ? null : investorMargin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.EXCHANGE_MARGIN
     *
     * @return the value of T_TRANSACTION_STATISTICS.EXCHANGE_MARGIN
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getExchangeMargin() {
        return exchangeMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.EXCHANGE_MARGIN
     *
     * @param exchangeMargin the value for T_TRANSACTION_STATISTICS.EXCHANGE_MARGIN
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setExchangeMargin(String exchangeMargin) {
        this.exchangeMargin = exchangeMargin == null ? null : exchangeMargin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.LONG_OPTION_VALUE
     *
     * @return the value of T_TRANSACTION_STATISTICS.LONG_OPTION_VALUE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getLongOptionValue() {
        return longOptionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.LONG_OPTION_VALUE
     *
     * @param longOptionValue the value for T_TRANSACTION_STATISTICS.LONG_OPTION_VALUE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setLongOptionValue(String longOptionValue) {
        this.longOptionValue = longOptionValue == null ? null : longOptionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.SHORT_OPTION_VALUE
     *
     * @return the value of T_TRANSACTION_STATISTICS.SHORT_OPTION_VALUE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getShortOptionValue() {
        return shortOptionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.SHORT_OPTION_VALUE
     *
     * @param shortOptionValue the value for T_TRANSACTION_STATISTICS.SHORT_OPTION_VALUE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setShortOptionValue(String shortOptionValue) {
        this.shortOptionValue = shortOptionValue == null ? null : shortOptionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.ROYALTY_INCOME
     *
     * @return the value of T_TRANSACTION_STATISTICS.ROYALTY_INCOME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getRoyaltyIncome() {
        return royaltyIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.ROYALTY_INCOME
     *
     * @param royaltyIncome the value for T_TRANSACTION_STATISTICS.ROYALTY_INCOME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setRoyaltyIncome(String royaltyIncome) {
        this.royaltyIncome = royaltyIncome == null ? null : royaltyIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.ROYALTY_PAYMENT
     *
     * @return the value of T_TRANSACTION_STATISTICS.ROYALTY_PAYMENT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getRoyaltyPayment() {
        return royaltyPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.ROYALTY_PAYMENT
     *
     * @param royaltyPayment the value for T_TRANSACTION_STATISTICS.ROYALTY_PAYMENT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setRoyaltyPayment(String royaltyPayment) {
        this.royaltyPayment = royaltyPayment == null ? null : royaltyPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.EXCHANGE_EXERCISE_CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.EXCHANGE_EXERCISE_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getExchangeExerciseCharge() {
        return exchangeExerciseCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.EXCHANGE_EXERCISE_CHARGE
     *
     * @param exchangeExerciseCharge the value for T_TRANSACTION_STATISTICS.EXCHANGE_EXERCISE_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setExchangeExerciseCharge(String exchangeExerciseCharge) {
        this.exchangeExerciseCharge = exchangeExerciseCharge == null ? null : exchangeExerciseCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.EXERCISE_CHARGE
     *
     * @return the value of T_TRANSACTION_STATISTICS.EXERCISE_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getExerciseCharge() {
        return exerciseCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.EXERCISE_CHARGE
     *
     * @param exerciseCharge the value for T_TRANSACTION_STATISTICS.EXERCISE_CHARGE
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setExerciseCharge(String exerciseCharge) {
        this.exerciseCharge = exerciseCharge == null ? null : exerciseCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.EXERCISE_PROFIT
     *
     * @return the value of T_TRANSACTION_STATISTICS.EXERCISE_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getExerciseProfit() {
        return exerciseProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.EXERCISE_PROFIT
     *
     * @param exerciseProfit the value for T_TRANSACTION_STATISTICS.EXERCISE_PROFIT
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setExerciseProfit(String exerciseProfit) {
        this.exerciseProfit = exerciseProfit == null ? null : exerciseProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.BATCH_NO
     *
     * @return the value of T_TRANSACTION_STATISTICS.BATCH_NO
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.BATCH_NO
     *
     * @param batchNo the value for T_TRANSACTION_STATISTICS.BATCH_NO
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.CREATE_TIME
     *
     * @return the value of T_TRANSACTION_STATISTICS.CREATE_TIME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.CREATE_TIME
     *
     * @param createTime the value for T_TRANSACTION_STATISTICS.CREATE_TIME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRANSACTION_STATISTICS.UPDATE_TIME
     *
     * @return the value of T_TRANSACTION_STATISTICS.UPDATE_TIME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRANSACTION_STATISTICS.UPDATE_TIME
     *
     * @param updateTime the value for T_TRANSACTION_STATISTICS.UPDATE_TIME
     *
     * @mbggenerated Wed Apr 05 13:50:46 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}