package com.bohai.dataCenter.entity;

import java.math.BigDecimal;

public class VTradeDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.TRADE_DATE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.INVESTOR_NO
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.SERIAL_NO
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.INSTRUMENT
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private String instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.VOLUME
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private Long volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.DEAL_PRICE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private BigDecimal dealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.TURNOVER
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private BigDecimal turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.OFFSET_FLAG
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private String offsetFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.HADGE_FLAG
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private String hadgeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.EXCHANGE_ID
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private String exchangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.CLOSE_TODAY
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private Short closeToday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.CLOSE_YESTERDAY
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private Short closeYesterday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_TRADE_DETAIL.CHARGE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    private BigDecimal charge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.TRADE_DATE
     *
     * @return the value of V_TRADE_DETAIL.TRADE_DATE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.TRADE_DATE
     *
     * @param tradeDate the value for V_TRADE_DETAIL.TRADE_DATE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.INVESTOR_NO
     *
     * @return the value of V_TRADE_DETAIL.INVESTOR_NO
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.INVESTOR_NO
     *
     * @param investorNo the value for V_TRADE_DETAIL.INVESTOR_NO
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.SERIAL_NO
     *
     * @return the value of V_TRADE_DETAIL.SERIAL_NO
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.SERIAL_NO
     *
     * @param serialNo the value for V_TRADE_DETAIL.SERIAL_NO
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.INSTRUMENT
     *
     * @return the value of V_TRADE_DETAIL.INSTRUMENT
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.INSTRUMENT
     *
     * @param instrument the value for V_TRADE_DETAIL.INSTRUMENT
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument == null ? null : instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.VOLUME
     *
     * @return the value of V_TRADE_DETAIL.VOLUME
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.VOLUME
     *
     * @param volume the value for V_TRADE_DETAIL.VOLUME
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.DEAL_PRICE
     *
     * @return the value of V_TRADE_DETAIL.DEAL_PRICE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public BigDecimal getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.DEAL_PRICE
     *
     * @param dealPrice the value for V_TRADE_DETAIL.DEAL_PRICE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setDealPrice(BigDecimal dealPrice) {
        this.dealPrice = dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.TURNOVER
     *
     * @return the value of V_TRADE_DETAIL.TURNOVER
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public BigDecimal getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.TURNOVER
     *
     * @param turnover the value for V_TRADE_DETAIL.TURNOVER
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setTurnover(BigDecimal turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.OFFSET_FLAG
     *
     * @return the value of V_TRADE_DETAIL.OFFSET_FLAG
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public String getOffsetFlag() {
        return offsetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.OFFSET_FLAG
     *
     * @param offsetFlag the value for V_TRADE_DETAIL.OFFSET_FLAG
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setOffsetFlag(String offsetFlag) {
        this.offsetFlag = offsetFlag == null ? null : offsetFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.HADGE_FLAG
     *
     * @return the value of V_TRADE_DETAIL.HADGE_FLAG
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public String getHadgeFlag() {
        return hadgeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.HADGE_FLAG
     *
     * @param hadgeFlag the value for V_TRADE_DETAIL.HADGE_FLAG
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setHadgeFlag(String hadgeFlag) {
        this.hadgeFlag = hadgeFlag == null ? null : hadgeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.EXCHANGE_ID
     *
     * @return the value of V_TRADE_DETAIL.EXCHANGE_ID
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public String getExchangeId() {
        return exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.EXCHANGE_ID
     *
     * @param exchangeId the value for V_TRADE_DETAIL.EXCHANGE_ID
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setExchangeId(String exchangeId) {
        this.exchangeId = exchangeId == null ? null : exchangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.CLOSE_TODAY
     *
     * @return the value of V_TRADE_DETAIL.CLOSE_TODAY
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public Short getCloseToday() {
        return closeToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.CLOSE_TODAY
     *
     * @param closeToday the value for V_TRADE_DETAIL.CLOSE_TODAY
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setCloseToday(Short closeToday) {
        this.closeToday = closeToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.CLOSE_YESTERDAY
     *
     * @return the value of V_TRADE_DETAIL.CLOSE_YESTERDAY
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public Short getCloseYesterday() {
        return closeYesterday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.CLOSE_YESTERDAY
     *
     * @param closeYesterday the value for V_TRADE_DETAIL.CLOSE_YESTERDAY
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setCloseYesterday(Short closeYesterday) {
        this.closeYesterday = closeYesterday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_TRADE_DETAIL.CHARGE
     *
     * @return the value of V_TRADE_DETAIL.CHARGE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_TRADE_DETAIL.CHARGE
     *
     * @param charge the value for V_TRADE_DETAIL.CHARGE
     *
     * @mbggenerated Wed Apr 19 10:36:43 CST 2017
     */
    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }
}