package com.bohai.dataCenter.vo;

public class CrmMediatorAndCustomer {
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER.INVESTOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER.INVESTOR_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String mediatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.MEDIATOR_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String mediatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MEDIATOR.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String remark;

    private String effectDate;
    
    private String expireDate;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @return the value of T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @param marketerName the value for T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @return the value of T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @param marketerName the value for T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName == null ? null : investorName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MARKETER.MEDIATOR_NO
     *
     * @return the value of T_CRM_MARKETER.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getMediatorNo() {
        return mediatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MARKETER.MEDIATOR_NO
     *
     * @param marketerName the value for T_CRM_MARKETER.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setMediatorNo(String mediatorNo) {
        this.mediatorNo = mediatorNo == null ? null : mediatorNo.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MARKETER.MARKETER_NAME
     *
     * @return the value of T_CRM_MARKETER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getMediatorName() {
        return mediatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MARKETER.MARKETER_NAME
     *
     * @param marketerName the value for T_CRM_MARKETER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setMediatorName(String mediatorName) {
        this.mediatorName = mediatorName == null ? null : mediatorName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MARKETER.REMARK
     *
     * @return the value of T_CRM_MARKETER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MARKETER.REMARK
     *
     * @param marketerName the value for T_CRM_MARKETER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    
    public String getEffectDate() {
        return effectDate;
    }
    
    public void setEffectDate(String effectDate) {
        this.effectDate = effectDate == null ? null : effectDate.trim();
    }
    
    public String getExpireDate() {
        return expireDate;
    }
    
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate == null ? null : expireDate.trim();
    }
    

}