package com.bohai.dataCenter.vo;

public class CrmMarketerAndCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MARKETER.MARKETER_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String marketerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_MARKETER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String marketerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER.INVESTOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String investorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER.INVESTOR_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CRM_CUSTOMER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MARKETER.MARKETER_NO
     *
     * @return the value of T_CRM_MARKETER.MARKETER_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getMarketerNo() {
        return marketerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MARKETER.MARKETER_NO
     *
     * @param marketerNo the value for T_CRM_MARKETER.MARKETER_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setMarketerNo(String marketerNo) {
        this.marketerNo = marketerNo == null ? null : marketerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_MARKETER.MARKETER_NAME
     *
     * @return the value of T_CRM_MARKETER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getMarketerName() {
        return marketerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_MARKETER.MARKETER_NAME
     *
     * @param marketerName the value for T_CRM_MARKETER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setMarketerName(String marketerName) {
        this.marketerName = marketerName == null ? null : marketerName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @return the value of T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getInvestorNo() {
        return investorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @param marketerName the value for T_CRM_CUSTOMER.MEDIATOR_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setInvestorNo(String investorNo) {
        this.investorNo = investorNo == null ? null : investorNo.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @return the value of T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @param marketerName the value for T_CRM_CUSTOMER.MARKETER_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName == null ? null : investorName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CRM_CUSTOMER.REMARK
     *
     * @return the value of T_CRM_CUSTOMER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CRM_CUSTOMER.REMARK
     *
     * @param marketerName the value for T_CRM_CUSTOMER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    

}